/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
)


// VarConsoleApiService VarConsoleApi service
type VarConsoleApiService service

type ApiVarConsoleGetPartnerUsageRequest struct {
	ctx context.Context
	ApiService *VarConsoleApiService
	ks *string
	format *int32
	clientTag *string
	partnerId *int32
	body *VarConsoleGetPartnerUsageRequest
}

func (r ApiVarConsoleGetPartnerUsageRequest) Ks(ks string) ApiVarConsoleGetPartnerUsageRequest {
	r.ks = &ks
	return r
}

// The format of the response
func (r ApiVarConsoleGetPartnerUsageRequest) Format(format int32) ApiVarConsoleGetPartnerUsageRequest {
	r.format = &format
	return r
}

func (r ApiVarConsoleGetPartnerUsageRequest) ClientTag(clientTag string) ApiVarConsoleGetPartnerUsageRequest {
	r.clientTag = &clientTag
	return r
}

func (r ApiVarConsoleGetPartnerUsageRequest) PartnerId(partnerId int32) ApiVarConsoleGetPartnerUsageRequest {
	r.partnerId = &partnerId
	return r
}

func (r ApiVarConsoleGetPartnerUsageRequest) Body(body VarConsoleGetPartnerUsageRequest) ApiVarConsoleGetPartnerUsageRequest {
	r.body = &body
	return r
}

func (r ApiVarConsoleGetPartnerUsageRequest) Execute() (*KalturaPartnerUsageListResponse, *http.Response, error) {
	return r.ApiService.VarConsoleGetPartnerUsageExecute(r)
}

/*
VarConsoleGetPartnerUsage Method for VarConsoleGetPartnerUsage

Function which calulates partner usage of a group of a VAR's sub-publishers

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVarConsoleGetPartnerUsageRequest
*/
func (a *VarConsoleApiService) VarConsoleGetPartnerUsage(ctx context.Context) ApiVarConsoleGetPartnerUsageRequest {
	return ApiVarConsoleGetPartnerUsageRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return KalturaPartnerUsageListResponse
func (a *VarConsoleApiService) VarConsoleGetPartnerUsageExecute(r ApiVarConsoleGetPartnerUsageRequest) (*KalturaPartnerUsageListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *KalturaPartnerUsageListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VarConsoleApiService.VarConsoleGetPartnerUsage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/service/varconsole_varconsole/action/getPartnerUsage"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.ks != nil {
		localVarQueryParams.Add("ks", parameterToString(*r.ks, ""))
	}
	if r.format != nil {
		localVarQueryParams.Add("format", parameterToString(*r.format, ""))
	}
	if r.clientTag != nil {
		localVarQueryParams.Add("clientTag", parameterToString(*r.clientTag, ""))
	}
	if r.partnerId != nil {
		localVarQueryParams.Add("partnerId", parameterToString(*r.partnerId, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ks"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("ks", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiVarConsoleUpdateStatusRequest struct {
	ctx context.Context
	ApiService *VarConsoleApiService
	ks *string
	format *int32
	clientTag *string
	partnerId *int32
	body *VarConsoleUpdateStatusRequest
}

func (r ApiVarConsoleUpdateStatusRequest) Ks(ks string) ApiVarConsoleUpdateStatusRequest {
	r.ks = &ks
	return r
}

// The format of the response
func (r ApiVarConsoleUpdateStatusRequest) Format(format int32) ApiVarConsoleUpdateStatusRequest {
	r.format = &format
	return r
}

func (r ApiVarConsoleUpdateStatusRequest) ClientTag(clientTag string) ApiVarConsoleUpdateStatusRequest {
	r.clientTag = &clientTag
	return r
}

func (r ApiVarConsoleUpdateStatusRequest) PartnerId(partnerId int32) ApiVarConsoleUpdateStatusRequest {
	r.partnerId = &partnerId
	return r
}

func (r ApiVarConsoleUpdateStatusRequest) Body(body VarConsoleUpdateStatusRequest) ApiVarConsoleUpdateStatusRequest {
	r.body = &body
	return r
}

func (r ApiVarConsoleUpdateStatusRequest) Execute() (*http.Response, error) {
	return r.ApiService.VarConsoleUpdateStatusExecute(r)
}

/*
VarConsoleUpdateStatus Method for VarConsoleUpdateStatus

Function to change a sub-publisher's status

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiVarConsoleUpdateStatusRequest
*/
func (a *VarConsoleApiService) VarConsoleUpdateStatus(ctx context.Context) ApiVarConsoleUpdateStatusRequest {
	return ApiVarConsoleUpdateStatusRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *VarConsoleApiService) VarConsoleUpdateStatusExecute(r ApiVarConsoleUpdateStatusRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "VarConsoleApiService.VarConsoleUpdateStatus")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/service/varconsole_varconsole/action/updateStatus"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.ks != nil {
		localVarQueryParams.Add("ks", parameterToString(*r.ks, ""))
	}
	if r.format != nil {
		localVarQueryParams.Add("format", parameterToString(*r.format, ""))
	}
	if r.clientTag != nil {
		localVarQueryParams.Add("clientTag", parameterToString(*r.clientTag, ""))
	}
	if r.partnerId != nil {
		localVarQueryParams.Add("partnerId", parameterToString(*r.partnerId, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ks"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("ks", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
