/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
)


// FlavorParamsOutputApiService FlavorParamsOutputApi service
type FlavorParamsOutputApiService service

type ApiFlavorParamsOutputGetRequest struct {
	ctx context.Context
	ApiService *FlavorParamsOutputApiService
	ks *string
	format *int32
	clientTag *string
	partnerId *int32
	body *AccessControlDeleteRequest
}

func (r ApiFlavorParamsOutputGetRequest) Ks(ks string) ApiFlavorParamsOutputGetRequest {
	r.ks = &ks
	return r
}

// The format of the response
func (r ApiFlavorParamsOutputGetRequest) Format(format int32) ApiFlavorParamsOutputGetRequest {
	r.format = &format
	return r
}

func (r ApiFlavorParamsOutputGetRequest) ClientTag(clientTag string) ApiFlavorParamsOutputGetRequest {
	r.clientTag = &clientTag
	return r
}

func (r ApiFlavorParamsOutputGetRequest) PartnerId(partnerId int32) ApiFlavorParamsOutputGetRequest {
	r.partnerId = &partnerId
	return r
}

func (r ApiFlavorParamsOutputGetRequest) Body(body AccessControlDeleteRequest) ApiFlavorParamsOutputGetRequest {
	r.body = &body
	return r
}

func (r ApiFlavorParamsOutputGetRequest) Execute() (*KalturaFlavorParamsOutput, *http.Response, error) {
	return r.ApiService.FlavorParamsOutputGetExecute(r)
}

/*
FlavorParamsOutputGet Method for FlavorParamsOutputGet

Get flavor params output object by ID

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiFlavorParamsOutputGetRequest
*/
func (a *FlavorParamsOutputApiService) FlavorParamsOutputGet(ctx context.Context) ApiFlavorParamsOutputGetRequest {
	return ApiFlavorParamsOutputGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return KalturaFlavorParamsOutput
func (a *FlavorParamsOutputApiService) FlavorParamsOutputGetExecute(r ApiFlavorParamsOutputGetRequest) (*KalturaFlavorParamsOutput, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *KalturaFlavorParamsOutput
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FlavorParamsOutputApiService.FlavorParamsOutputGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/service/flavorparamsoutput/action/get"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.ks != nil {
		localVarQueryParams.Add("ks", parameterToString(*r.ks, ""))
	}
	if r.format != nil {
		localVarQueryParams.Add("format", parameterToString(*r.format, ""))
	}
	if r.clientTag != nil {
		localVarQueryParams.Add("clientTag", parameterToString(*r.clientTag, ""))
	}
	if r.partnerId != nil {
		localVarQueryParams.Add("partnerId", parameterToString(*r.partnerId, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ks"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("ks", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiFlavorParamsOutputListRequest struct {
	ctx context.Context
	ApiService *FlavorParamsOutputApiService
	ks *string
	format *int32
	clientTag *string
	partnerId *int32
	body *FlavorParamsOutputListRequest
}

func (r ApiFlavorParamsOutputListRequest) Ks(ks string) ApiFlavorParamsOutputListRequest {
	r.ks = &ks
	return r
}

// The format of the response
func (r ApiFlavorParamsOutputListRequest) Format(format int32) ApiFlavorParamsOutputListRequest {
	r.format = &format
	return r
}

func (r ApiFlavorParamsOutputListRequest) ClientTag(clientTag string) ApiFlavorParamsOutputListRequest {
	r.clientTag = &clientTag
	return r
}

func (r ApiFlavorParamsOutputListRequest) PartnerId(partnerId int32) ApiFlavorParamsOutputListRequest {
	r.partnerId = &partnerId
	return r
}

func (r ApiFlavorParamsOutputListRequest) Body(body FlavorParamsOutputListRequest) ApiFlavorParamsOutputListRequest {
	r.body = &body
	return r
}

func (r ApiFlavorParamsOutputListRequest) Execute() (*KalturaFlavorParamsOutputListResponse, *http.Response, error) {
	return r.ApiService.FlavorParamsOutputListExecute(r)
}

/*
FlavorParamsOutputList Method for FlavorParamsOutputList

List flavor params output objects by filter and pager

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiFlavorParamsOutputListRequest
*/
func (a *FlavorParamsOutputApiService) FlavorParamsOutputList(ctx context.Context) ApiFlavorParamsOutputListRequest {
	return ApiFlavorParamsOutputListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return KalturaFlavorParamsOutputListResponse
func (a *FlavorParamsOutputApiService) FlavorParamsOutputListExecute(r ApiFlavorParamsOutputListRequest) (*KalturaFlavorParamsOutputListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *KalturaFlavorParamsOutputListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FlavorParamsOutputApiService.FlavorParamsOutputList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/service/flavorparamsoutput/action/list"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.ks != nil {
		localVarQueryParams.Add("ks", parameterToString(*r.ks, ""))
	}
	if r.format != nil {
		localVarQueryParams.Add("format", parameterToString(*r.format, ""))
	}
	if r.clientTag != nil {
		localVarQueryParams.Add("clientTag", parameterToString(*r.clientTag, ""))
	}
	if r.partnerId != nil {
		localVarQueryParams.Add("partnerId", parameterToString(*r.partnerId, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ks"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("ks", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
