/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaEntryIdentifier struct for KalturaEntryIdentifier
type KalturaEntryIdentifier struct {
	KalturaObjectIdentifier
}

// NewKalturaEntryIdentifier instantiates a new KalturaEntryIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaEntryIdentifier() *KalturaEntryIdentifier {
	this := KalturaEntryIdentifier{}
	return &this
}

// NewKalturaEntryIdentifierWithDefaults instantiates a new KalturaEntryIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaEntryIdentifierWithDefaults() *KalturaEntryIdentifier {
	this := KalturaEntryIdentifier{}
	return &this
}

func (o KalturaEntryIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaObjectIdentifier, errKalturaObjectIdentifier := json.Marshal(o.KalturaObjectIdentifier)
	if errKalturaObjectIdentifier != nil {
		return []byte{}, errKalturaObjectIdentifier
	}
	errKalturaObjectIdentifier = json.Unmarshal([]byte(serializedKalturaObjectIdentifier), &toSerialize)
	if errKalturaObjectIdentifier != nil {
		return []byte{}, errKalturaObjectIdentifier
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaEntryIdentifier struct {
	value *KalturaEntryIdentifier
	isSet bool
}

func (v NullableKalturaEntryIdentifier) Get() *KalturaEntryIdentifier {
	return v.value
}

func (v *NullableKalturaEntryIdentifier) Set(val *KalturaEntryIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaEntryIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaEntryIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaEntryIdentifier(val *KalturaEntryIdentifier) *NullableKalturaEntryIdentifier {
	return &NullableKalturaEntryIdentifier{value: val, isSet: true}
}

func (v NullableKalturaEntryIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaEntryIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


