/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ExternalMediaCountRequest struct for ExternalMediaCountRequest
type ExternalMediaCountRequest struct {
	Filter *KalturaExternalMediaEntryFilter `json:"filter,omitempty"`
}

// NewExternalMediaCountRequest instantiates a new ExternalMediaCountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalMediaCountRequest() *ExternalMediaCountRequest {
	this := ExternalMediaCountRequest{}
	return &this
}

// NewExternalMediaCountRequestWithDefaults instantiates a new ExternalMediaCountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalMediaCountRequestWithDefaults() *ExternalMediaCountRequest {
	this := ExternalMediaCountRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *ExternalMediaCountRequest) GetFilter() KalturaExternalMediaEntryFilter {
	if o == nil || o.Filter == nil {
		var ret KalturaExternalMediaEntryFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalMediaCountRequest) GetFilterOk() (*KalturaExternalMediaEntryFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ExternalMediaCountRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given KalturaExternalMediaEntryFilter and assigns it to the Filter field.
func (o *ExternalMediaCountRequest) SetFilter(v KalturaExternalMediaEntryFilter) {
	o.Filter = &v
}

func (o ExternalMediaCountRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	return json.Marshal(toSerialize)
}

type NullableExternalMediaCountRequest struct {
	value *ExternalMediaCountRequest
	isSet bool
}

func (v NullableExternalMediaCountRequest) Get() *ExternalMediaCountRequest {
	return v.value
}

func (v *NullableExternalMediaCountRequest) Set(val *ExternalMediaCountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalMediaCountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalMediaCountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalMediaCountRequest(val *ExternalMediaCountRequest) *NullableExternalMediaCountRequest {
	return &NullableExternalMediaCountRequest{value: val, isSet: true}
}

func (v NullableExternalMediaCountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalMediaCountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


