/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaYouTubeDistributionProviderFilter struct for KalturaYouTubeDistributionProviderFilter
type KalturaYouTubeDistributionProviderFilter struct {
	KalturaYouTubeDistributionProviderBaseFilter
}

// NewKalturaYouTubeDistributionProviderFilter instantiates a new KalturaYouTubeDistributionProviderFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaYouTubeDistributionProviderFilter() *KalturaYouTubeDistributionProviderFilter {
	this := KalturaYouTubeDistributionProviderFilter{}
	return &this
}

// NewKalturaYouTubeDistributionProviderFilterWithDefaults instantiates a new KalturaYouTubeDistributionProviderFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaYouTubeDistributionProviderFilterWithDefaults() *KalturaYouTubeDistributionProviderFilter {
	this := KalturaYouTubeDistributionProviderFilter{}
	return &this
}

func (o KalturaYouTubeDistributionProviderFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaYouTubeDistributionProviderBaseFilter, errKalturaYouTubeDistributionProviderBaseFilter := json.Marshal(o.KalturaYouTubeDistributionProviderBaseFilter)
	if errKalturaYouTubeDistributionProviderBaseFilter != nil {
		return []byte{}, errKalturaYouTubeDistributionProviderBaseFilter
	}
	errKalturaYouTubeDistributionProviderBaseFilter = json.Unmarshal([]byte(serializedKalturaYouTubeDistributionProviderBaseFilter), &toSerialize)
	if errKalturaYouTubeDistributionProviderBaseFilter != nil {
		return []byte{}, errKalturaYouTubeDistributionProviderBaseFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaYouTubeDistributionProviderFilter struct {
	value *KalturaYouTubeDistributionProviderFilter
	isSet bool
}

func (v NullableKalturaYouTubeDistributionProviderFilter) Get() *KalturaYouTubeDistributionProviderFilter {
	return v.value
}

func (v *NullableKalturaYouTubeDistributionProviderFilter) Set(val *KalturaYouTubeDistributionProviderFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaYouTubeDistributionProviderFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaYouTubeDistributionProviderFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaYouTubeDistributionProviderFilter(val *KalturaYouTubeDistributionProviderFilter) *NullableKalturaYouTubeDistributionProviderFilter {
	return &NullableKalturaYouTubeDistributionProviderFilter{value: val, isSet: true}
}

func (v NullableKalturaYouTubeDistributionProviderFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaYouTubeDistributionProviderFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


