/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LiveStreamAddRequest struct for LiveStreamAddRequest
type LiveStreamAddRequest struct {
	LiveStreamEntry KalturaLiveStreamEntry `json:"liveStreamEntry"`
	SourceType *string `json:"sourceType,omitempty"`
}

// NewLiveStreamAddRequest instantiates a new LiveStreamAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveStreamAddRequest(liveStreamEntry KalturaLiveStreamEntry) *LiveStreamAddRequest {
	this := LiveStreamAddRequest{}
	this.LiveStreamEntry = liveStreamEntry
	return &this
}

// NewLiveStreamAddRequestWithDefaults instantiates a new LiveStreamAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveStreamAddRequestWithDefaults() *LiveStreamAddRequest {
	this := LiveStreamAddRequest{}
	return &this
}

// GetLiveStreamEntry returns the LiveStreamEntry field value
func (o *LiveStreamAddRequest) GetLiveStreamEntry() KalturaLiveStreamEntry {
	if o == nil {
		var ret KalturaLiveStreamEntry
		return ret
	}

	return o.LiveStreamEntry
}

// GetLiveStreamEntryOk returns a tuple with the LiveStreamEntry field value
// and a boolean to check if the value has been set.
func (o *LiveStreamAddRequest) GetLiveStreamEntryOk() (*KalturaLiveStreamEntry, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiveStreamEntry, true
}

// SetLiveStreamEntry sets field value
func (o *LiveStreamAddRequest) SetLiveStreamEntry(v KalturaLiveStreamEntry) {
	o.LiveStreamEntry = v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *LiveStreamAddRequest) GetSourceType() string {
	if o == nil || o.SourceType == nil {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamAddRequest) GetSourceTypeOk() (*string, bool) {
	if o == nil || o.SourceType == nil {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *LiveStreamAddRequest) HasSourceType() bool {
	if o != nil && o.SourceType != nil {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *LiveStreamAddRequest) SetSourceType(v string) {
	o.SourceType = &v
}

func (o LiveStreamAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["liveStreamEntry"] = o.LiveStreamEntry
	}
	if o.SourceType != nil {
		toSerialize["sourceType"] = o.SourceType
	}
	return json.Marshal(toSerialize)
}

type NullableLiveStreamAddRequest struct {
	value *LiveStreamAddRequest
	isSet bool
}

func (v NullableLiveStreamAddRequest) Get() *LiveStreamAddRequest {
	return v.value
}

func (v *NullableLiveStreamAddRequest) Set(val *LiveStreamAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveStreamAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveStreamAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveStreamAddRequest(val *LiveStreamAddRequest) *NullableLiveStreamAddRequest {
	return &NullableLiveStreamAddRequest{value: val, isSet: true}
}

func (v NullableLiveStreamAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiveStreamAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


