/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VirusScanProfileDeleteRequest struct for VirusScanProfileDeleteRequest
type VirusScanProfileDeleteRequest struct {
	VirusScanProfileId int32 `json:"virusScanProfileId"`
}

// NewVirusScanProfileDeleteRequest instantiates a new VirusScanProfileDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirusScanProfileDeleteRequest(virusScanProfileId int32) *VirusScanProfileDeleteRequest {
	this := VirusScanProfileDeleteRequest{}
	this.VirusScanProfileId = virusScanProfileId
	return &this
}

// NewVirusScanProfileDeleteRequestWithDefaults instantiates a new VirusScanProfileDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirusScanProfileDeleteRequestWithDefaults() *VirusScanProfileDeleteRequest {
	this := VirusScanProfileDeleteRequest{}
	return &this
}

// GetVirusScanProfileId returns the VirusScanProfileId field value
func (o *VirusScanProfileDeleteRequest) GetVirusScanProfileId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VirusScanProfileId
}

// GetVirusScanProfileIdOk returns a tuple with the VirusScanProfileId field value
// and a boolean to check if the value has been set.
func (o *VirusScanProfileDeleteRequest) GetVirusScanProfileIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VirusScanProfileId, true
}

// SetVirusScanProfileId sets field value
func (o *VirusScanProfileDeleteRequest) SetVirusScanProfileId(v int32) {
	o.VirusScanProfileId = v
}

func (o VirusScanProfileDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["virusScanProfileId"] = o.VirusScanProfileId
	}
	return json.Marshal(toSerialize)
}

type NullableVirusScanProfileDeleteRequest struct {
	value *VirusScanProfileDeleteRequest
	isSet bool
}

func (v NullableVirusScanProfileDeleteRequest) Get() *VirusScanProfileDeleteRequest {
	return v.value
}

func (v *NullableVirusScanProfileDeleteRequest) Set(val *VirusScanProfileDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVirusScanProfileDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVirusScanProfileDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirusScanProfileDeleteRequest(val *VirusScanProfileDeleteRequest) *NullableVirusScanProfileDeleteRequest {
	return &NullableVirusScanProfileDeleteRequest{value: val, isSet: true}
}

func (v NullableVirusScanProfileDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirusScanProfileDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


