/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaBulkServiceData `abstract`  This class represents object-specific data passed to the   bulk upload job.
type KalturaBulkServiceData struct {
	ObjectType *string `json:"objectType,omitempty"`
}

// NewKalturaBulkServiceData instantiates a new KalturaBulkServiceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaBulkServiceData() *KalturaBulkServiceData {
	this := KalturaBulkServiceData{}
	return &this
}

// NewKalturaBulkServiceDataWithDefaults instantiates a new KalturaBulkServiceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaBulkServiceDataWithDefaults() *KalturaBulkServiceData {
	this := KalturaBulkServiceData{}
	return &this
}

// GetObjectType returns the ObjectType field value if set, zero value otherwise.
func (o *KalturaBulkServiceData) GetObjectType() string {
	if o == nil || o.ObjectType == nil {
		var ret string
		return ret
	}
	return *o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaBulkServiceData) GetObjectTypeOk() (*string, bool) {
	if o == nil || o.ObjectType == nil {
		return nil, false
	}
	return o.ObjectType, true
}

// HasObjectType returns a boolean if a field has been set.
func (o *KalturaBulkServiceData) HasObjectType() bool {
	if o != nil && o.ObjectType != nil {
		return true
	}

	return false
}

// SetObjectType gets a reference to the given string and assigns it to the ObjectType field.
func (o *KalturaBulkServiceData) SetObjectType(v string) {
	o.ObjectType = &v
}

func (o KalturaBulkServiceData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ObjectType != nil {
		toSerialize["objectType"] = o.ObjectType
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaBulkServiceData struct {
	value *KalturaBulkServiceData
	isSet bool
}

func (v NullableKalturaBulkServiceData) Get() *KalturaBulkServiceData {
	return v.value
}

func (v *NullableKalturaBulkServiceData) Set(val *KalturaBulkServiceData) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaBulkServiceData) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaBulkServiceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaBulkServiceData(val *KalturaBulkServiceData) *NullableKalturaBulkServiceData {
	return &NullableKalturaBulkServiceData{value: val, isSet: true}
}

func (v NullableKalturaBulkServiceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaBulkServiceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


