/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaESearchUserParams struct for KalturaESearchUserParams
type KalturaESearchUserParams struct {
	KalturaESearchParams
}

// NewKalturaESearchUserParams instantiates a new KalturaESearchUserParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaESearchUserParams() *KalturaESearchUserParams {
	this := KalturaESearchUserParams{}
	return &this
}

// NewKalturaESearchUserParamsWithDefaults instantiates a new KalturaESearchUserParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaESearchUserParamsWithDefaults() *KalturaESearchUserParams {
	this := KalturaESearchUserParams{}
	return &this
}

func (o KalturaESearchUserParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaESearchParams, errKalturaESearchParams := json.Marshal(o.KalturaESearchParams)
	if errKalturaESearchParams != nil {
		return []byte{}, errKalturaESearchParams
	}
	errKalturaESearchParams = json.Unmarshal([]byte(serializedKalturaESearchParams), &toSerialize)
	if errKalturaESearchParams != nil {
		return []byte{}, errKalturaESearchParams
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaESearchUserParams struct {
	value *KalturaESearchUserParams
	isSet bool
}

func (v NullableKalturaESearchUserParams) Get() *KalturaESearchUserParams {
	return v.value
}

func (v *NullableKalturaESearchUserParams) Set(val *KalturaESearchUserParams) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaESearchUserParams) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaESearchUserParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaESearchUserParams(val *KalturaESearchUserParams) *NullableKalturaESearchUserParams {
	return &NullableKalturaESearchUserParams{value: val, isSet: true}
}

func (v NullableKalturaESearchUserParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaESearchUserParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


