/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaLiveChannelSegment struct for KalturaLiveChannelSegment
type KalturaLiveChannelSegment struct {
	// Live channel id
	ChannelId *string `json:"channelId,omitempty"`
	// `readOnly`  Segment creation date as Unix timestamp (In seconds)
	CreatedAt *int32 `json:"createdAt,omitempty"`
	// Segment description
	Description *string `json:"description,omitempty"`
	// Segment play duration time, in mili-seconds
	Duration *float32 `json:"duration,omitempty"`
	// Entry id to be played
	EntryId *string `json:"entryId,omitempty"`
	// `readOnly`  Unique identifier
	Id *int32 `json:"id,omitempty"`
	// Segment name
	Name *string `json:"name,omitempty"`
	// `readOnly`
	PartnerId *int32 `json:"partnerId,omitempty"`
	// Segment play start time, in mili-seconds, according to trigger type
	StartTime *float32 `json:"startTime,omitempty"`
	// `readOnly`  Enum Type: `KalturaLiveChannelSegmentStatus`
	Status *string `json:"status,omitempty"`
	// Segment tags
	Tags *string `json:"tags,omitempty"`
	// Live channel segment that the trigger relates to
	TriggerSegmentId *int32 `json:"triggerSegmentId,omitempty"`
	// Enum Type: `KalturaLiveChannelSegmentTriggerType`  Segment start time trigger type
	TriggerType *string `json:"triggerType,omitempty"`
	// Enum Type: `KalturaLiveChannelSegmentType`  Segment could be associated with the main stream, as additional stream or as overlay
	Type *string `json:"type,omitempty"`
	// `readOnly`  Segment update date as Unix timestamp (In seconds)
	UpdatedAt *int32 `json:"updatedAt,omitempty"`
}

// NewKalturaLiveChannelSegment instantiates a new KalturaLiveChannelSegment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaLiveChannelSegment() *KalturaLiveChannelSegment {
	this := KalturaLiveChannelSegment{}
	return &this
}

// NewKalturaLiveChannelSegmentWithDefaults instantiates a new KalturaLiveChannelSegment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaLiveChannelSegmentWithDefaults() *KalturaLiveChannelSegment {
	this := KalturaLiveChannelSegment{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetChannelId() string {
	if o == nil || o.ChannelId == nil {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetChannelIdOk() (*string, bool) {
	if o == nil || o.ChannelId == nil {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasChannelId() bool {
	if o != nil && o.ChannelId != nil {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *KalturaLiveChannelSegment) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetCreatedAt() int32 {
	if o == nil || o.CreatedAt == nil {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetCreatedAtOk() (*int32, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *KalturaLiveChannelSegment) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *KalturaLiveChannelSegment) SetDescription(v string) {
	o.Description = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetDuration() float32 {
	if o == nil || o.Duration == nil {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetDurationOk() (*float32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *KalturaLiveChannelSegment) SetDuration(v float32) {
	o.Duration = &v
}

// GetEntryId returns the EntryId field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetEntryId() string {
	if o == nil || o.EntryId == nil {
		var ret string
		return ret
	}
	return *o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetEntryIdOk() (*string, bool) {
	if o == nil || o.EntryId == nil {
		return nil, false
	}
	return o.EntryId, true
}

// HasEntryId returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasEntryId() bool {
	if o != nil && o.EntryId != nil {
		return true
	}

	return false
}

// SetEntryId gets a reference to the given string and assigns it to the EntryId field.
func (o *KalturaLiveChannelSegment) SetEntryId(v string) {
	o.EntryId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *KalturaLiveChannelSegment) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *KalturaLiveChannelSegment) SetName(v string) {
	o.Name = &v
}

// GetPartnerId returns the PartnerId field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetPartnerId() int32 {
	if o == nil || o.PartnerId == nil {
		var ret int32
		return ret
	}
	return *o.PartnerId
}

// GetPartnerIdOk returns a tuple with the PartnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetPartnerIdOk() (*int32, bool) {
	if o == nil || o.PartnerId == nil {
		return nil, false
	}
	return o.PartnerId, true
}

// HasPartnerId returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasPartnerId() bool {
	if o != nil && o.PartnerId != nil {
		return true
	}

	return false
}

// SetPartnerId gets a reference to the given int32 and assigns it to the PartnerId field.
func (o *KalturaLiveChannelSegment) SetPartnerId(v int32) {
	o.PartnerId = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetStartTime() float32 {
	if o == nil || o.StartTime == nil {
		var ret float32
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetStartTimeOk() (*float32, bool) {
	if o == nil || o.StartTime == nil {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasStartTime() bool {
	if o != nil && o.StartTime != nil {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given float32 and assigns it to the StartTime field.
func (o *KalturaLiveChannelSegment) SetStartTime(v float32) {
	o.StartTime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *KalturaLiveChannelSegment) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetTags() string {
	if o == nil || o.Tags == nil {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetTagsOk() (*string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *KalturaLiveChannelSegment) SetTags(v string) {
	o.Tags = &v
}

// GetTriggerSegmentId returns the TriggerSegmentId field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetTriggerSegmentId() int32 {
	if o == nil || o.TriggerSegmentId == nil {
		var ret int32
		return ret
	}
	return *o.TriggerSegmentId
}

// GetTriggerSegmentIdOk returns a tuple with the TriggerSegmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetTriggerSegmentIdOk() (*int32, bool) {
	if o == nil || o.TriggerSegmentId == nil {
		return nil, false
	}
	return o.TriggerSegmentId, true
}

// HasTriggerSegmentId returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasTriggerSegmentId() bool {
	if o != nil && o.TriggerSegmentId != nil {
		return true
	}

	return false
}

// SetTriggerSegmentId gets a reference to the given int32 and assigns it to the TriggerSegmentId field.
func (o *KalturaLiveChannelSegment) SetTriggerSegmentId(v int32) {
	o.TriggerSegmentId = &v
}

// GetTriggerType returns the TriggerType field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetTriggerType() string {
	if o == nil || o.TriggerType == nil {
		var ret string
		return ret
	}
	return *o.TriggerType
}

// GetTriggerTypeOk returns a tuple with the TriggerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetTriggerTypeOk() (*string, bool) {
	if o == nil || o.TriggerType == nil {
		return nil, false
	}
	return o.TriggerType, true
}

// HasTriggerType returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasTriggerType() bool {
	if o != nil && o.TriggerType != nil {
		return true
	}

	return false
}

// SetTriggerType gets a reference to the given string and assigns it to the TriggerType field.
func (o *KalturaLiveChannelSegment) SetTriggerType(v string) {
	o.TriggerType = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *KalturaLiveChannelSegment) SetType(v string) {
	o.Type = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *KalturaLiveChannelSegment) GetUpdatedAt() int32 {
	if o == nil || o.UpdatedAt == nil {
		var ret int32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaLiveChannelSegment) GetUpdatedAtOk() (*int32, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *KalturaLiveChannelSegment) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int32 and assigns it to the UpdatedAt field.
func (o *KalturaLiveChannelSegment) SetUpdatedAt(v int32) {
	o.UpdatedAt = &v
}

func (o KalturaLiveChannelSegment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ChannelId != nil {
		toSerialize["channelId"] = o.ChannelId
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Duration != nil {
		toSerialize["duration"] = o.Duration
	}
	if o.EntryId != nil {
		toSerialize["entryId"] = o.EntryId
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.PartnerId != nil {
		toSerialize["partnerId"] = o.PartnerId
	}
	if o.StartTime != nil {
		toSerialize["startTime"] = o.StartTime
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.TriggerSegmentId != nil {
		toSerialize["triggerSegmentId"] = o.TriggerSegmentId
	}
	if o.TriggerType != nil {
		toSerialize["triggerType"] = o.TriggerType
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaLiveChannelSegment struct {
	value *KalturaLiveChannelSegment
	isSet bool
}

func (v NullableKalturaLiveChannelSegment) Get() *KalturaLiveChannelSegment {
	return v.value
}

func (v *NullableKalturaLiveChannelSegment) Set(val *KalturaLiveChannelSegment) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaLiveChannelSegment) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaLiveChannelSegment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaLiveChannelSegment(val *KalturaLiveChannelSegment) *NullableKalturaLiveChannelSegment {
	return &NullableKalturaLiveChannelSegment{value: val, isSet: true}
}

func (v NullableKalturaLiveChannelSegment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaLiveChannelSegment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


