/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaSyndicationDistributionProfileBaseFilter `abstract`
type KalturaSyndicationDistributionProfileBaseFilter struct {
	KalturaDistributionProfileFilter
}

// NewKalturaSyndicationDistributionProfileBaseFilter instantiates a new KalturaSyndicationDistributionProfileBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaSyndicationDistributionProfileBaseFilter() *KalturaSyndicationDistributionProfileBaseFilter {
	this := KalturaSyndicationDistributionProfileBaseFilter{}
	return &this
}

// NewKalturaSyndicationDistributionProfileBaseFilterWithDefaults instantiates a new KalturaSyndicationDistributionProfileBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaSyndicationDistributionProfileBaseFilterWithDefaults() *KalturaSyndicationDistributionProfileBaseFilter {
	this := KalturaSyndicationDistributionProfileBaseFilter{}
	return &this
}

func (o KalturaSyndicationDistributionProfileBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaDistributionProfileFilter, errKalturaDistributionProfileFilter := json.Marshal(o.KalturaDistributionProfileFilter)
	if errKalturaDistributionProfileFilter != nil {
		return []byte{}, errKalturaDistributionProfileFilter
	}
	errKalturaDistributionProfileFilter = json.Unmarshal([]byte(serializedKalturaDistributionProfileFilter), &toSerialize)
	if errKalturaDistributionProfileFilter != nil {
		return []byte{}, errKalturaDistributionProfileFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaSyndicationDistributionProfileBaseFilter struct {
	value *KalturaSyndicationDistributionProfileBaseFilter
	isSet bool
}

func (v NullableKalturaSyndicationDistributionProfileBaseFilter) Get() *KalturaSyndicationDistributionProfileBaseFilter {
	return v.value
}

func (v *NullableKalturaSyndicationDistributionProfileBaseFilter) Set(val *KalturaSyndicationDistributionProfileBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaSyndicationDistributionProfileBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaSyndicationDistributionProfileBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaSyndicationDistributionProfileBaseFilter(val *KalturaSyndicationDistributionProfileBaseFilter) *NullableKalturaSyndicationDistributionProfileBaseFilter {
	return &NullableKalturaSyndicationDistributionProfileBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaSyndicationDistributionProfileBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaSyndicationDistributionProfileBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


