/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaGenericXsltSyndicationFeedBaseFilter `abstract`
type KalturaGenericXsltSyndicationFeedBaseFilter struct {
	KalturaGenericSyndicationFeedFilter
}

// NewKalturaGenericXsltSyndicationFeedBaseFilter instantiates a new KalturaGenericXsltSyndicationFeedBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaGenericXsltSyndicationFeedBaseFilter() *KalturaGenericXsltSyndicationFeedBaseFilter {
	this := KalturaGenericXsltSyndicationFeedBaseFilter{}
	return &this
}

// NewKalturaGenericXsltSyndicationFeedBaseFilterWithDefaults instantiates a new KalturaGenericXsltSyndicationFeedBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaGenericXsltSyndicationFeedBaseFilterWithDefaults() *KalturaGenericXsltSyndicationFeedBaseFilter {
	this := KalturaGenericXsltSyndicationFeedBaseFilter{}
	return &this
}

func (o KalturaGenericXsltSyndicationFeedBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaGenericSyndicationFeedFilter, errKalturaGenericSyndicationFeedFilter := json.Marshal(o.KalturaGenericSyndicationFeedFilter)
	if errKalturaGenericSyndicationFeedFilter != nil {
		return []byte{}, errKalturaGenericSyndicationFeedFilter
	}
	errKalturaGenericSyndicationFeedFilter = json.Unmarshal([]byte(serializedKalturaGenericSyndicationFeedFilter), &toSerialize)
	if errKalturaGenericSyndicationFeedFilter != nil {
		return []byte{}, errKalturaGenericSyndicationFeedFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaGenericXsltSyndicationFeedBaseFilter struct {
	value *KalturaGenericXsltSyndicationFeedBaseFilter
	isSet bool
}

func (v NullableKalturaGenericXsltSyndicationFeedBaseFilter) Get() *KalturaGenericXsltSyndicationFeedBaseFilter {
	return v.value
}

func (v *NullableKalturaGenericXsltSyndicationFeedBaseFilter) Set(val *KalturaGenericXsltSyndicationFeedBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaGenericXsltSyndicationFeedBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaGenericXsltSyndicationFeedBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaGenericXsltSyndicationFeedBaseFilter(val *KalturaGenericXsltSyndicationFeedBaseFilter) *NullableKalturaGenericXsltSyndicationFeedBaseFilter {
	return &NullableKalturaGenericXsltSyndicationFeedBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaGenericXsltSyndicationFeedBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaGenericXsltSyndicationFeedBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


