/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LiveReportsGetEventsRequest struct for LiveReportsGetEventsRequest
type LiveReportsGetEventsRequest struct {
	Filter *KalturaLiveReportInputFilter `json:"filter,omitempty"`
	Pager *KalturaFilterPager `json:"pager,omitempty"`
	ReportType string `json:"reportType"`
}

// NewLiveReportsGetEventsRequest instantiates a new LiveReportsGetEventsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveReportsGetEventsRequest(reportType string) *LiveReportsGetEventsRequest {
	this := LiveReportsGetEventsRequest{}
	this.ReportType = reportType
	return &this
}

// NewLiveReportsGetEventsRequestWithDefaults instantiates a new LiveReportsGetEventsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveReportsGetEventsRequestWithDefaults() *LiveReportsGetEventsRequest {
	this := LiveReportsGetEventsRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *LiveReportsGetEventsRequest) GetFilter() KalturaLiveReportInputFilter {
	if o == nil || o.Filter == nil {
		var ret KalturaLiveReportInputFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveReportsGetEventsRequest) GetFilterOk() (*KalturaLiveReportInputFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *LiveReportsGetEventsRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given KalturaLiveReportInputFilter and assigns it to the Filter field.
func (o *LiveReportsGetEventsRequest) SetFilter(v KalturaLiveReportInputFilter) {
	o.Filter = &v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *LiveReportsGetEventsRequest) GetPager() KalturaFilterPager {
	if o == nil || o.Pager == nil {
		var ret KalturaFilterPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveReportsGetEventsRequest) GetPagerOk() (*KalturaFilterPager, bool) {
	if o == nil || o.Pager == nil {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *LiveReportsGetEventsRequest) HasPager() bool {
	if o != nil && o.Pager != nil {
		return true
	}

	return false
}

// SetPager gets a reference to the given KalturaFilterPager and assigns it to the Pager field.
func (o *LiveReportsGetEventsRequest) SetPager(v KalturaFilterPager) {
	o.Pager = &v
}

// GetReportType returns the ReportType field value
func (o *LiveReportsGetEventsRequest) GetReportType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReportType
}

// GetReportTypeOk returns a tuple with the ReportType field value
// and a boolean to check if the value has been set.
func (o *LiveReportsGetEventsRequest) GetReportTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportType, true
}

// SetReportType sets field value
func (o *LiveReportsGetEventsRequest) SetReportType(v string) {
	o.ReportType = v
}

func (o LiveReportsGetEventsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Pager != nil {
		toSerialize["pager"] = o.Pager
	}
	if true {
		toSerialize["reportType"] = o.ReportType
	}
	return json.Marshal(toSerialize)
}

type NullableLiveReportsGetEventsRequest struct {
	value *LiveReportsGetEventsRequest
	isSet bool
}

func (v NullableLiveReportsGetEventsRequest) Get() *LiveReportsGetEventsRequest {
	return v.value
}

func (v *NullableLiveReportsGetEventsRequest) Set(val *LiveReportsGetEventsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveReportsGetEventsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveReportsGetEventsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveReportsGetEventsRequest(val *LiveReportsGetEventsRequest) *NullableLiveReportsGetEventsRequest {
	return &NullableLiveReportsGetEventsRequest{value: val, isSet: true}
}

func (v NullableLiveReportsGetEventsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiveReportsGetEventsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


