/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaPlayReadyCopyEnablerHolder struct for KalturaPlayReadyCopyEnablerHolder
type KalturaPlayReadyCopyEnablerHolder struct {
	// Enum Type: `KalturaPlayReadyCopyEnablerType`  The type of the copy enabler
	Type *string `json:"type,omitempty"`
}

// NewKalturaPlayReadyCopyEnablerHolder instantiates a new KalturaPlayReadyCopyEnablerHolder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaPlayReadyCopyEnablerHolder() *KalturaPlayReadyCopyEnablerHolder {
	this := KalturaPlayReadyCopyEnablerHolder{}
	return &this
}

// NewKalturaPlayReadyCopyEnablerHolderWithDefaults instantiates a new KalturaPlayReadyCopyEnablerHolder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaPlayReadyCopyEnablerHolderWithDefaults() *KalturaPlayReadyCopyEnablerHolder {
	this := KalturaPlayReadyCopyEnablerHolder{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *KalturaPlayReadyCopyEnablerHolder) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaPlayReadyCopyEnablerHolder) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *KalturaPlayReadyCopyEnablerHolder) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *KalturaPlayReadyCopyEnablerHolder) SetType(v string) {
	o.Type = &v
}

func (o KalturaPlayReadyCopyEnablerHolder) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaPlayReadyCopyEnablerHolder struct {
	value *KalturaPlayReadyCopyEnablerHolder
	isSet bool
}

func (v NullableKalturaPlayReadyCopyEnablerHolder) Get() *KalturaPlayReadyCopyEnablerHolder {
	return v.value
}

func (v *NullableKalturaPlayReadyCopyEnablerHolder) Set(val *KalturaPlayReadyCopyEnablerHolder) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaPlayReadyCopyEnablerHolder) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaPlayReadyCopyEnablerHolder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaPlayReadyCopyEnablerHolder(val *KalturaPlayReadyCopyEnablerHolder) *NullableKalturaPlayReadyCopyEnablerHolder {
	return &NullableKalturaPlayReadyCopyEnablerHolder{value: val, isSet: true}
}

func (v NullableKalturaPlayReadyCopyEnablerHolder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaPlayReadyCopyEnablerHolder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


