/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaEntryLiveStats struct for KalturaEntryLiveStats
type KalturaEntryLiveStats struct {
	KalturaLiveStats
}

// NewKalturaEntryLiveStats instantiates a new KalturaEntryLiveStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaEntryLiveStats() *KalturaEntryLiveStats {
	this := KalturaEntryLiveStats{}
	return &this
}

// NewKalturaEntryLiveStatsWithDefaults instantiates a new KalturaEntryLiveStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaEntryLiveStatsWithDefaults() *KalturaEntryLiveStats {
	this := KalturaEntryLiveStats{}
	return &this
}

func (o KalturaEntryLiveStats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaLiveStats, errKalturaLiveStats := json.Marshal(o.KalturaLiveStats)
	if errKalturaLiveStats != nil {
		return []byte{}, errKalturaLiveStats
	}
	errKalturaLiveStats = json.Unmarshal([]byte(serializedKalturaLiveStats), &toSerialize)
	if errKalturaLiveStats != nil {
		return []byte{}, errKalturaLiveStats
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaEntryLiveStats struct {
	value *KalturaEntryLiveStats
	isSet bool
}

func (v NullableKalturaEntryLiveStats) Get() *KalturaEntryLiveStats {
	return v.value
}

func (v *NullableKalturaEntryLiveStats) Set(val *KalturaEntryLiveStats) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaEntryLiveStats) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaEntryLiveStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaEntryLiveStats(val *KalturaEntryLiveStats) *NullableKalturaEntryLiveStats {
	return &NullableKalturaEntryLiveStats{value: val, isSet: true}
}

func (v NullableKalturaEntryLiveStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaEntryLiveStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


