/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaDropFolderContentProcessorJobData struct for KalturaDropFolderContentProcessorJobData
type KalturaDropFolderContentProcessorJobData struct {
	KalturaJobData
}

// NewKalturaDropFolderContentProcessorJobData instantiates a new KalturaDropFolderContentProcessorJobData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaDropFolderContentProcessorJobData() *KalturaDropFolderContentProcessorJobData {
	this := KalturaDropFolderContentProcessorJobData{}
	return &this
}

// NewKalturaDropFolderContentProcessorJobDataWithDefaults instantiates a new KalturaDropFolderContentProcessorJobData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaDropFolderContentProcessorJobDataWithDefaults() *KalturaDropFolderContentProcessorJobData {
	this := KalturaDropFolderContentProcessorJobData{}
	return &this
}

func (o KalturaDropFolderContentProcessorJobData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaJobData, errKalturaJobData := json.Marshal(o.KalturaJobData)
	if errKalturaJobData != nil {
		return []byte{}, errKalturaJobData
	}
	errKalturaJobData = json.Unmarshal([]byte(serializedKalturaJobData), &toSerialize)
	if errKalturaJobData != nil {
		return []byte{}, errKalturaJobData
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaDropFolderContentProcessorJobData struct {
	value *KalturaDropFolderContentProcessorJobData
	isSet bool
}

func (v NullableKalturaDropFolderContentProcessorJobData) Get() *KalturaDropFolderContentProcessorJobData {
	return v.value
}

func (v *NullableKalturaDropFolderContentProcessorJobData) Set(val *KalturaDropFolderContentProcessorJobData) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaDropFolderContentProcessorJobData) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaDropFolderContentProcessorJobData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaDropFolderContentProcessorJobData(val *KalturaDropFolderContentProcessorJobData) *NullableKalturaDropFolderContentProcessorJobData {
	return &NullableKalturaDropFolderContentProcessorJobData{value: val, isSet: true}
}

func (v NullableKalturaDropFolderContentProcessorJobData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaDropFolderContentProcessorJobData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


