/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaDataCenterContentResource `abstract`
type KalturaDataCenterContentResource struct {
	KalturaContentResource
}

// NewKalturaDataCenterContentResource instantiates a new KalturaDataCenterContentResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaDataCenterContentResource() *KalturaDataCenterContentResource {
	this := KalturaDataCenterContentResource{}
	return &this
}

// NewKalturaDataCenterContentResourceWithDefaults instantiates a new KalturaDataCenterContentResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaDataCenterContentResourceWithDefaults() *KalturaDataCenterContentResource {
	this := KalturaDataCenterContentResource{}
	return &this
}

func (o KalturaDataCenterContentResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaContentResource, errKalturaContentResource := json.Marshal(o.KalturaContentResource)
	if errKalturaContentResource != nil {
		return []byte{}, errKalturaContentResource
	}
	errKalturaContentResource = json.Unmarshal([]byte(serializedKalturaContentResource), &toSerialize)
	if errKalturaContentResource != nil {
		return []byte{}, errKalturaContentResource
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaDataCenterContentResource struct {
	value *KalturaDataCenterContentResource
	isSet bool
}

func (v NullableKalturaDataCenterContentResource) Get() *KalturaDataCenterContentResource {
	return v.value
}

func (v *NullableKalturaDataCenterContentResource) Set(val *KalturaDataCenterContentResource) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaDataCenterContentResource) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaDataCenterContentResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaDataCenterContentResource(val *KalturaDataCenterContentResource) *NullableKalturaDataCenterContentResource {
	return &NullableKalturaDataCenterContentResource{value: val, isSet: true}
}

func (v NullableKalturaDataCenterContentResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaDataCenterContentResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


