/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EventNotificationTemplateAddRequest struct for EventNotificationTemplateAddRequest
type EventNotificationTemplateAddRequest struct {
	EventNotificationTemplate KalturaEventNotificationTemplate `json:"eventNotificationTemplate"`
}

// NewEventNotificationTemplateAddRequest instantiates a new EventNotificationTemplateAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventNotificationTemplateAddRequest(eventNotificationTemplate KalturaEventNotificationTemplate) *EventNotificationTemplateAddRequest {
	this := EventNotificationTemplateAddRequest{}
	this.EventNotificationTemplate = eventNotificationTemplate
	return &this
}

// NewEventNotificationTemplateAddRequestWithDefaults instantiates a new EventNotificationTemplateAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventNotificationTemplateAddRequestWithDefaults() *EventNotificationTemplateAddRequest {
	this := EventNotificationTemplateAddRequest{}
	return &this
}

// GetEventNotificationTemplate returns the EventNotificationTemplate field value
func (o *EventNotificationTemplateAddRequest) GetEventNotificationTemplate() KalturaEventNotificationTemplate {
	if o == nil {
		var ret KalturaEventNotificationTemplate
		return ret
	}

	return o.EventNotificationTemplate
}

// GetEventNotificationTemplateOk returns a tuple with the EventNotificationTemplate field value
// and a boolean to check if the value has been set.
func (o *EventNotificationTemplateAddRequest) GetEventNotificationTemplateOk() (*KalturaEventNotificationTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventNotificationTemplate, true
}

// SetEventNotificationTemplate sets field value
func (o *EventNotificationTemplateAddRequest) SetEventNotificationTemplate(v KalturaEventNotificationTemplate) {
	o.EventNotificationTemplate = v
}

func (o EventNotificationTemplateAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["eventNotificationTemplate"] = o.EventNotificationTemplate
	}
	return json.Marshal(toSerialize)
}

type NullableEventNotificationTemplateAddRequest struct {
	value *EventNotificationTemplateAddRequest
	isSet bool
}

func (v NullableEventNotificationTemplateAddRequest) Get() *EventNotificationTemplateAddRequest {
	return v.value
}

func (v *NullableEventNotificationTemplateAddRequest) Set(val *EventNotificationTemplateAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEventNotificationTemplateAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEventNotificationTemplateAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventNotificationTemplateAddRequest(val *EventNotificationTemplateAddRequest) *NullableEventNotificationTemplateAddRequest {
	return &NullableEventNotificationTemplateAddRequest{value: val, isSet: true}
}

func (v NullableEventNotificationTemplateAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventNotificationTemplateAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


