/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaSynacorHboDistributionProviderFilter struct for KalturaSynacorHboDistributionProviderFilter
type KalturaSynacorHboDistributionProviderFilter struct {
	KalturaSynacorHboDistributionProviderBaseFilter
}

// NewKalturaSynacorHboDistributionProviderFilter instantiates a new KalturaSynacorHboDistributionProviderFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaSynacorHboDistributionProviderFilter() *KalturaSynacorHboDistributionProviderFilter {
	this := KalturaSynacorHboDistributionProviderFilter{}
	return &this
}

// NewKalturaSynacorHboDistributionProviderFilterWithDefaults instantiates a new KalturaSynacorHboDistributionProviderFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaSynacorHboDistributionProviderFilterWithDefaults() *KalturaSynacorHboDistributionProviderFilter {
	this := KalturaSynacorHboDistributionProviderFilter{}
	return &this
}

func (o KalturaSynacorHboDistributionProviderFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaSynacorHboDistributionProviderBaseFilter, errKalturaSynacorHboDistributionProviderBaseFilter := json.Marshal(o.KalturaSynacorHboDistributionProviderBaseFilter)
	if errKalturaSynacorHboDistributionProviderBaseFilter != nil {
		return []byte{}, errKalturaSynacorHboDistributionProviderBaseFilter
	}
	errKalturaSynacorHboDistributionProviderBaseFilter = json.Unmarshal([]byte(serializedKalturaSynacorHboDistributionProviderBaseFilter), &toSerialize)
	if errKalturaSynacorHboDistributionProviderBaseFilter != nil {
		return []byte{}, errKalturaSynacorHboDistributionProviderBaseFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaSynacorHboDistributionProviderFilter struct {
	value *KalturaSynacorHboDistributionProviderFilter
	isSet bool
}

func (v NullableKalturaSynacorHboDistributionProviderFilter) Get() *KalturaSynacorHboDistributionProviderFilter {
	return v.value
}

func (v *NullableKalturaSynacorHboDistributionProviderFilter) Set(val *KalturaSynacorHboDistributionProviderFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaSynacorHboDistributionProviderFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaSynacorHboDistributionProviderFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaSynacorHboDistributionProviderFilter(val *KalturaSynacorHboDistributionProviderFilter) *NullableKalturaSynacorHboDistributionProviderFilter {
	return &NullableKalturaSynacorHboDistributionProviderFilter{value: val, isSet: true}
}

func (v NullableKalturaSynacorHboDistributionProviderFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaSynacorHboDistributionProviderFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


