/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BusinessProcessServerAddRequest struct for BusinessProcessServerAddRequest
type BusinessProcessServerAddRequest struct {
	BusinessProcessServer KalturaBusinessProcessServer `json:"businessProcessServer"`
}

// NewBusinessProcessServerAddRequest instantiates a new BusinessProcessServerAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBusinessProcessServerAddRequest(businessProcessServer KalturaBusinessProcessServer) *BusinessProcessServerAddRequest {
	this := BusinessProcessServerAddRequest{}
	this.BusinessProcessServer = businessProcessServer
	return &this
}

// NewBusinessProcessServerAddRequestWithDefaults instantiates a new BusinessProcessServerAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBusinessProcessServerAddRequestWithDefaults() *BusinessProcessServerAddRequest {
	this := BusinessProcessServerAddRequest{}
	return &this
}

// GetBusinessProcessServer returns the BusinessProcessServer field value
func (o *BusinessProcessServerAddRequest) GetBusinessProcessServer() KalturaBusinessProcessServer {
	if o == nil {
		var ret KalturaBusinessProcessServer
		return ret
	}

	return o.BusinessProcessServer
}

// GetBusinessProcessServerOk returns a tuple with the BusinessProcessServer field value
// and a boolean to check if the value has been set.
func (o *BusinessProcessServerAddRequest) GetBusinessProcessServerOk() (*KalturaBusinessProcessServer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BusinessProcessServer, true
}

// SetBusinessProcessServer sets field value
func (o *BusinessProcessServerAddRequest) SetBusinessProcessServer(v KalturaBusinessProcessServer) {
	o.BusinessProcessServer = v
}

func (o BusinessProcessServerAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["businessProcessServer"] = o.BusinessProcessServer
	}
	return json.Marshal(toSerialize)
}

type NullableBusinessProcessServerAddRequest struct {
	value *BusinessProcessServerAddRequest
	isSet bool
}

func (v NullableBusinessProcessServerAddRequest) Get() *BusinessProcessServerAddRequest {
	return v.value
}

func (v *NullableBusinessProcessServerAddRequest) Set(val *BusinessProcessServerAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessProcessServerAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessProcessServerAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessProcessServerAddRequest(val *BusinessProcessServerAddRequest) *NullableBusinessProcessServerAddRequest {
	return &NullableBusinessProcessServerAddRequest{value: val, isSet: true}
}

func (v NullableBusinessProcessServerAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessProcessServerAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


