/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaZoomDropFolderFilter struct for KalturaZoomDropFolderFilter
type KalturaZoomDropFolderFilter struct {
	KalturaZoomDropFolderBaseFilter
}

// NewKalturaZoomDropFolderFilter instantiates a new KalturaZoomDropFolderFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaZoomDropFolderFilter() *KalturaZoomDropFolderFilter {
	this := KalturaZoomDropFolderFilter{}
	return &this
}

// NewKalturaZoomDropFolderFilterWithDefaults instantiates a new KalturaZoomDropFolderFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaZoomDropFolderFilterWithDefaults() *KalturaZoomDropFolderFilter {
	this := KalturaZoomDropFolderFilter{}
	return &this
}

func (o KalturaZoomDropFolderFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaZoomDropFolderBaseFilter, errKalturaZoomDropFolderBaseFilter := json.Marshal(o.KalturaZoomDropFolderBaseFilter)
	if errKalturaZoomDropFolderBaseFilter != nil {
		return []byte{}, errKalturaZoomDropFolderBaseFilter
	}
	errKalturaZoomDropFolderBaseFilter = json.Unmarshal([]byte(serializedKalturaZoomDropFolderBaseFilter), &toSerialize)
	if errKalturaZoomDropFolderBaseFilter != nil {
		return []byte{}, errKalturaZoomDropFolderBaseFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaZoomDropFolderFilter struct {
	value *KalturaZoomDropFolderFilter
	isSet bool
}

func (v NullableKalturaZoomDropFolderFilter) Get() *KalturaZoomDropFolderFilter {
	return v.value
}

func (v *NullableKalturaZoomDropFolderFilter) Set(val *KalturaZoomDropFolderFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaZoomDropFolderFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaZoomDropFolderFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaZoomDropFolderFilter(val *KalturaZoomDropFolderFilter) *NullableKalturaZoomDropFolderFilter {
	return &NullableKalturaZoomDropFolderFilter{value: val, isSet: true}
}

func (v NullableKalturaZoomDropFolderFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaZoomDropFolderFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


