/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaSchedulerWorkerListResponse struct for KalturaSchedulerWorkerListResponse
type KalturaSchedulerWorkerListResponse struct {
	KalturaListResponse
}

// NewKalturaSchedulerWorkerListResponse instantiates a new KalturaSchedulerWorkerListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaSchedulerWorkerListResponse() *KalturaSchedulerWorkerListResponse {
	this := KalturaSchedulerWorkerListResponse{}
	return &this
}

// NewKalturaSchedulerWorkerListResponseWithDefaults instantiates a new KalturaSchedulerWorkerListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaSchedulerWorkerListResponseWithDefaults() *KalturaSchedulerWorkerListResponse {
	this := KalturaSchedulerWorkerListResponse{}
	return &this
}

func (o KalturaSchedulerWorkerListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaListResponse, errKalturaListResponse := json.Marshal(o.KalturaListResponse)
	if errKalturaListResponse != nil {
		return []byte{}, errKalturaListResponse
	}
	errKalturaListResponse = json.Unmarshal([]byte(serializedKalturaListResponse), &toSerialize)
	if errKalturaListResponse != nil {
		return []byte{}, errKalturaListResponse
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaSchedulerWorkerListResponse struct {
	value *KalturaSchedulerWorkerListResponse
	isSet bool
}

func (v NullableKalturaSchedulerWorkerListResponse) Get() *KalturaSchedulerWorkerListResponse {
	return v.value
}

func (v *NullableKalturaSchedulerWorkerListResponse) Set(val *KalturaSchedulerWorkerListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaSchedulerWorkerListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaSchedulerWorkerListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaSchedulerWorkerListResponse(val *KalturaSchedulerWorkerListResponse) *NullableKalturaSchedulerWorkerListResponse {
	return &NullableKalturaSchedulerWorkerListResponse{value: val, isSet: true}
}

func (v NullableKalturaSchedulerWorkerListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaSchedulerWorkerListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


