/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaS3DropFolderFile struct for KalturaS3DropFolderFile
type KalturaS3DropFolderFile struct {
	KalturaDropFolderFile
}

// NewKalturaS3DropFolderFile instantiates a new KalturaS3DropFolderFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaS3DropFolderFile() *KalturaS3DropFolderFile {
	this := KalturaS3DropFolderFile{}
	return &this
}

// NewKalturaS3DropFolderFileWithDefaults instantiates a new KalturaS3DropFolderFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaS3DropFolderFileWithDefaults() *KalturaS3DropFolderFile {
	this := KalturaS3DropFolderFile{}
	return &this
}

func (o KalturaS3DropFolderFile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaDropFolderFile, errKalturaDropFolderFile := json.Marshal(o.KalturaDropFolderFile)
	if errKalturaDropFolderFile != nil {
		return []byte{}, errKalturaDropFolderFile
	}
	errKalturaDropFolderFile = json.Unmarshal([]byte(serializedKalturaDropFolderFile), &toSerialize)
	if errKalturaDropFolderFile != nil {
		return []byte{}, errKalturaDropFolderFile
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaS3DropFolderFile struct {
	value *KalturaS3DropFolderFile
	isSet bool
}

func (v NullableKalturaS3DropFolderFile) Get() *KalturaS3DropFolderFile {
	return v.value
}

func (v *NullableKalturaS3DropFolderFile) Set(val *KalturaS3DropFolderFile) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaS3DropFolderFile) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaS3DropFolderFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaS3DropFolderFile(val *KalturaS3DropFolderFile) *NullableKalturaS3DropFolderFile {
	return &NullableKalturaS3DropFolderFile{value: val, isSet: true}
}

func (v NullableKalturaS3DropFolderFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaS3DropFolderFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


