/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResponseProfileUpdateStatusRequest struct for ResponseProfileUpdateStatusRequest
type ResponseProfileUpdateStatusRequest struct {
	Id int32 `json:"id"`
	Status int32 `json:"status"`
}

// NewResponseProfileUpdateStatusRequest instantiates a new ResponseProfileUpdateStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseProfileUpdateStatusRequest(id int32, status int32) *ResponseProfileUpdateStatusRequest {
	this := ResponseProfileUpdateStatusRequest{}
	this.Id = id
	this.Status = status
	return &this
}

// NewResponseProfileUpdateStatusRequestWithDefaults instantiates a new ResponseProfileUpdateStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseProfileUpdateStatusRequestWithDefaults() *ResponseProfileUpdateStatusRequest {
	this := ResponseProfileUpdateStatusRequest{}
	return &this
}

// GetId returns the Id field value
func (o *ResponseProfileUpdateStatusRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ResponseProfileUpdateStatusRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ResponseProfileUpdateStatusRequest) SetId(v int32) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *ResponseProfileUpdateStatusRequest) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ResponseProfileUpdateStatusRequest) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ResponseProfileUpdateStatusRequest) SetStatus(v int32) {
	o.Status = v
}

func (o ResponseProfileUpdateStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableResponseProfileUpdateStatusRequest struct {
	value *ResponseProfileUpdateStatusRequest
	isSet bool
}

func (v NullableResponseProfileUpdateStatusRequest) Get() *ResponseProfileUpdateStatusRequest {
	return v.value
}

func (v *NullableResponseProfileUpdateStatusRequest) Set(val *ResponseProfileUpdateStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseProfileUpdateStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseProfileUpdateStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseProfileUpdateStatusRequest(val *ResponseProfileUpdateStatusRequest) *NullableResponseProfileUpdateStatusRequest {
	return &NullableResponseProfileUpdateStatusRequest{value: val, isSet: true}
}

func (v NullableResponseProfileUpdateStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseProfileUpdateStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


