/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UserEntryListRequest struct for UserEntryListRequest
type UserEntryListRequest struct {
	Filter *KalturaUserEntryFilter `json:"filter,omitempty"`
	Pager *KalturaFilterPager `json:"pager,omitempty"`
}

// NewUserEntryListRequest instantiates a new UserEntryListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserEntryListRequest() *UserEntryListRequest {
	this := UserEntryListRequest{}
	return &this
}

// NewUserEntryListRequestWithDefaults instantiates a new UserEntryListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserEntryListRequestWithDefaults() *UserEntryListRequest {
	this := UserEntryListRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *UserEntryListRequest) GetFilter() KalturaUserEntryFilter {
	if o == nil || o.Filter == nil {
		var ret KalturaUserEntryFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserEntryListRequest) GetFilterOk() (*KalturaUserEntryFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *UserEntryListRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given KalturaUserEntryFilter and assigns it to the Filter field.
func (o *UserEntryListRequest) SetFilter(v KalturaUserEntryFilter) {
	o.Filter = &v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *UserEntryListRequest) GetPager() KalturaFilterPager {
	if o == nil || o.Pager == nil {
		var ret KalturaFilterPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserEntryListRequest) GetPagerOk() (*KalturaFilterPager, bool) {
	if o == nil || o.Pager == nil {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *UserEntryListRequest) HasPager() bool {
	if o != nil && o.Pager != nil {
		return true
	}

	return false
}

// SetPager gets a reference to the given KalturaFilterPager and assigns it to the Pager field.
func (o *UserEntryListRequest) SetPager(v KalturaFilterPager) {
	o.Pager = &v
}

func (o UserEntryListRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Pager != nil {
		toSerialize["pager"] = o.Pager
	}
	return json.Marshal(toSerialize)
}

type NullableUserEntryListRequest struct {
	value *UserEntryListRequest
	isSet bool
}

func (v NullableUserEntryListRequest) Get() *UserEntryListRequest {
	return v.value
}

func (v *NullableUserEntryListRequest) Set(val *UserEntryListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserEntryListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserEntryListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserEntryListRequest(val *UserEntryListRequest) *NullableUserEntryListRequest {
	return &NullableUserEntryListRequest{value: val, isSet: true}
}

func (v NullableUserEntryListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserEntryListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


