/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaBusinessProcessServerBaseFilter `abstract`
type KalturaBusinessProcessServerBaseFilter struct {
	KalturaFilter
}

// NewKalturaBusinessProcessServerBaseFilter instantiates a new KalturaBusinessProcessServerBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaBusinessProcessServerBaseFilter() *KalturaBusinessProcessServerBaseFilter {
	this := KalturaBusinessProcessServerBaseFilter{}
	return &this
}

// NewKalturaBusinessProcessServerBaseFilterWithDefaults instantiates a new KalturaBusinessProcessServerBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaBusinessProcessServerBaseFilterWithDefaults() *KalturaBusinessProcessServerBaseFilter {
	this := KalturaBusinessProcessServerBaseFilter{}
	return &this
}

func (o KalturaBusinessProcessServerBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaFilter, errKalturaFilter := json.Marshal(o.KalturaFilter)
	if errKalturaFilter != nil {
		return []byte{}, errKalturaFilter
	}
	errKalturaFilter = json.Unmarshal([]byte(serializedKalturaFilter), &toSerialize)
	if errKalturaFilter != nil {
		return []byte{}, errKalturaFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaBusinessProcessServerBaseFilter struct {
	value *KalturaBusinessProcessServerBaseFilter
	isSet bool
}

func (v NullableKalturaBusinessProcessServerBaseFilter) Get() *KalturaBusinessProcessServerBaseFilter {
	return v.value
}

func (v *NullableKalturaBusinessProcessServerBaseFilter) Set(val *KalturaBusinessProcessServerBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaBusinessProcessServerBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaBusinessProcessServerBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaBusinessProcessServerBaseFilter(val *KalturaBusinessProcessServerBaseFilter) *NullableKalturaBusinessProcessServerBaseFilter {
	return &NullableKalturaBusinessProcessServerBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaBusinessProcessServerBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaBusinessProcessServerBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


