/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaAnswerCuePointFilter struct for KalturaAnswerCuePointFilter
type KalturaAnswerCuePointFilter struct {
	KalturaAnswerCuePointBaseFilter
}

// NewKalturaAnswerCuePointFilter instantiates a new KalturaAnswerCuePointFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaAnswerCuePointFilter() *KalturaAnswerCuePointFilter {
	this := KalturaAnswerCuePointFilter{}
	return &this
}

// NewKalturaAnswerCuePointFilterWithDefaults instantiates a new KalturaAnswerCuePointFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaAnswerCuePointFilterWithDefaults() *KalturaAnswerCuePointFilter {
	this := KalturaAnswerCuePointFilter{}
	return &this
}

func (o KalturaAnswerCuePointFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaAnswerCuePointBaseFilter, errKalturaAnswerCuePointBaseFilter := json.Marshal(o.KalturaAnswerCuePointBaseFilter)
	if errKalturaAnswerCuePointBaseFilter != nil {
		return []byte{}, errKalturaAnswerCuePointBaseFilter
	}
	errKalturaAnswerCuePointBaseFilter = json.Unmarshal([]byte(serializedKalturaAnswerCuePointBaseFilter), &toSerialize)
	if errKalturaAnswerCuePointBaseFilter != nil {
		return []byte{}, errKalturaAnswerCuePointBaseFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaAnswerCuePointFilter struct {
	value *KalturaAnswerCuePointFilter
	isSet bool
}

func (v NullableKalturaAnswerCuePointFilter) Get() *KalturaAnswerCuePointFilter {
	return v.value
}

func (v *NullableKalturaAnswerCuePointFilter) Set(val *KalturaAnswerCuePointFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaAnswerCuePointFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaAnswerCuePointFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaAnswerCuePointFilter(val *KalturaAnswerCuePointFilter) *NullableKalturaAnswerCuePointFilter {
	return &NullableKalturaAnswerCuePointFilter{value: val, isSet: true}
}

func (v NullableKalturaAnswerCuePointFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaAnswerCuePointFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


