/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaTypedArray `abstract`
type KalturaTypedArray struct {
	Count *int32 `json:"count,omitempty"`
}

// NewKalturaTypedArray instantiates a new KalturaTypedArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaTypedArray() *KalturaTypedArray {
	this := KalturaTypedArray{}
	return &this
}

// NewKalturaTypedArrayWithDefaults instantiates a new KalturaTypedArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaTypedArrayWithDefaults() *KalturaTypedArray {
	this := KalturaTypedArray{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *KalturaTypedArray) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaTypedArray) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *KalturaTypedArray) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *KalturaTypedArray) SetCount(v int32) {
	o.Count = &v
}

func (o KalturaTypedArray) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaTypedArray struct {
	value *KalturaTypedArray
	isSet bool
}

func (v NullableKalturaTypedArray) Get() *KalturaTypedArray {
	return v.value
}

func (v *NullableKalturaTypedArray) Set(val *KalturaTypedArray) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaTypedArray) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaTypedArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaTypedArray(val *KalturaTypedArray) *NullableKalturaTypedArray {
	return &NullableKalturaTypedArray{value: val, isSet: true}
}

func (v NullableKalturaTypedArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaTypedArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


