/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FileAssetSetContentRequest struct for FileAssetSetContentRequest
type FileAssetSetContentRequest struct {
	ContentResource KalturaContentResource `json:"contentResource"`
	Id int32 `json:"id"`
}

// NewFileAssetSetContentRequest instantiates a new FileAssetSetContentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileAssetSetContentRequest(contentResource KalturaContentResource, id int32) *FileAssetSetContentRequest {
	this := FileAssetSetContentRequest{}
	this.ContentResource = contentResource
	this.Id = id
	return &this
}

// NewFileAssetSetContentRequestWithDefaults instantiates a new FileAssetSetContentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileAssetSetContentRequestWithDefaults() *FileAssetSetContentRequest {
	this := FileAssetSetContentRequest{}
	return &this
}

// GetContentResource returns the ContentResource field value
func (o *FileAssetSetContentRequest) GetContentResource() KalturaContentResource {
	if o == nil {
		var ret KalturaContentResource
		return ret
	}

	return o.ContentResource
}

// GetContentResourceOk returns a tuple with the ContentResource field value
// and a boolean to check if the value has been set.
func (o *FileAssetSetContentRequest) GetContentResourceOk() (*KalturaContentResource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentResource, true
}

// SetContentResource sets field value
func (o *FileAssetSetContentRequest) SetContentResource(v KalturaContentResource) {
	o.ContentResource = v
}

// GetId returns the Id field value
func (o *FileAssetSetContentRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FileAssetSetContentRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FileAssetSetContentRequest) SetId(v int32) {
	o.Id = v
}

func (o FileAssetSetContentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["contentResource"] = o.ContentResource
	}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableFileAssetSetContentRequest struct {
	value *FileAssetSetContentRequest
	isSet bool
}

func (v NullableFileAssetSetContentRequest) Get() *FileAssetSetContentRequest {
	return v.value
}

func (v *NullableFileAssetSetContentRequest) Set(val *FileAssetSetContentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFileAssetSetContentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFileAssetSetContentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileAssetSetContentRequest(val *FileAssetSetContentRequest) *NullableFileAssetSetContentRequest {
	return &NullableFileAssetSetContentRequest{value: val, isSet: true}
}

func (v NullableFileAssetSetContentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileAssetSetContentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


