/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CaptureSpaceServeInstallRequest struct for CaptureSpaceServeInstallRequest
type CaptureSpaceServeInstallRequest struct {
	Os string `json:"os"`
}

// NewCaptureSpaceServeInstallRequest instantiates a new CaptureSpaceServeInstallRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptureSpaceServeInstallRequest(os string) *CaptureSpaceServeInstallRequest {
	this := CaptureSpaceServeInstallRequest{}
	this.Os = os
	return &this
}

// NewCaptureSpaceServeInstallRequestWithDefaults instantiates a new CaptureSpaceServeInstallRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptureSpaceServeInstallRequestWithDefaults() *CaptureSpaceServeInstallRequest {
	this := CaptureSpaceServeInstallRequest{}
	return &this
}

// GetOs returns the Os field value
func (o *CaptureSpaceServeInstallRequest) GetOs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Os
}

// GetOsOk returns a tuple with the Os field value
// and a boolean to check if the value has been set.
func (o *CaptureSpaceServeInstallRequest) GetOsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Os, true
}

// SetOs sets field value
func (o *CaptureSpaceServeInstallRequest) SetOs(v string) {
	o.Os = v
}

func (o CaptureSpaceServeInstallRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["os"] = o.Os
	}
	return json.Marshal(toSerialize)
}

type NullableCaptureSpaceServeInstallRequest struct {
	value *CaptureSpaceServeInstallRequest
	isSet bool
}

func (v NullableCaptureSpaceServeInstallRequest) Get() *CaptureSpaceServeInstallRequest {
	return v.value
}

func (v *NullableCaptureSpaceServeInstallRequest) Set(val *CaptureSpaceServeInstallRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptureSpaceServeInstallRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptureSpaceServeInstallRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptureSpaceServeInstallRequest(val *CaptureSpaceServeInstallRequest) *NullableCaptureSpaceServeInstallRequest {
	return &NullableCaptureSpaceServeInstallRequest{value: val, isSet: true}
}

func (v NullableCaptureSpaceServeInstallRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptureSpaceServeInstallRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


