/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ThumbAssetAddRequest struct for ThumbAssetAddRequest
type ThumbAssetAddRequest struct {
	EntryId string `json:"entryId"`
	ThumbAsset KalturaThumbAsset `json:"thumbAsset"`
}

// NewThumbAssetAddRequest instantiates a new ThumbAssetAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThumbAssetAddRequest(entryId string, thumbAsset KalturaThumbAsset) *ThumbAssetAddRequest {
	this := ThumbAssetAddRequest{}
	this.EntryId = entryId
	this.ThumbAsset = thumbAsset
	return &this
}

// NewThumbAssetAddRequestWithDefaults instantiates a new ThumbAssetAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThumbAssetAddRequestWithDefaults() *ThumbAssetAddRequest {
	this := ThumbAssetAddRequest{}
	return &this
}

// GetEntryId returns the EntryId field value
func (o *ThumbAssetAddRequest) GetEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value
// and a boolean to check if the value has been set.
func (o *ThumbAssetAddRequest) GetEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryId, true
}

// SetEntryId sets field value
func (o *ThumbAssetAddRequest) SetEntryId(v string) {
	o.EntryId = v
}

// GetThumbAsset returns the ThumbAsset field value
func (o *ThumbAssetAddRequest) GetThumbAsset() KalturaThumbAsset {
	if o == nil {
		var ret KalturaThumbAsset
		return ret
	}

	return o.ThumbAsset
}

// GetThumbAssetOk returns a tuple with the ThumbAsset field value
// and a boolean to check if the value has been set.
func (o *ThumbAssetAddRequest) GetThumbAssetOk() (*KalturaThumbAsset, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThumbAsset, true
}

// SetThumbAsset sets field value
func (o *ThumbAssetAddRequest) SetThumbAsset(v KalturaThumbAsset) {
	o.ThumbAsset = v
}

func (o ThumbAssetAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["entryId"] = o.EntryId
	}
	if true {
		toSerialize["thumbAsset"] = o.ThumbAsset
	}
	return json.Marshal(toSerialize)
}

type NullableThumbAssetAddRequest struct {
	value *ThumbAssetAddRequest
	isSet bool
}

func (v NullableThumbAssetAddRequest) Get() *ThumbAssetAddRequest {
	return v.value
}

func (v *NullableThumbAssetAddRequest) Set(val *ThumbAssetAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableThumbAssetAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableThumbAssetAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThumbAssetAddRequest(val *ThumbAssetAddRequest) *NullableThumbAssetAddRequest {
	return &NullableThumbAssetAddRequest{value: val, isSet: true}
}

func (v NullableThumbAssetAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThumbAssetAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


