/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaAvnDistributionProfileBaseFilter `abstract`
type KalturaAvnDistributionProfileBaseFilter struct {
	KalturaConfigurableDistributionProfileFilter
}

// NewKalturaAvnDistributionProfileBaseFilter instantiates a new KalturaAvnDistributionProfileBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaAvnDistributionProfileBaseFilter() *KalturaAvnDistributionProfileBaseFilter {
	this := KalturaAvnDistributionProfileBaseFilter{}
	return &this
}

// NewKalturaAvnDistributionProfileBaseFilterWithDefaults instantiates a new KalturaAvnDistributionProfileBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaAvnDistributionProfileBaseFilterWithDefaults() *KalturaAvnDistributionProfileBaseFilter {
	this := KalturaAvnDistributionProfileBaseFilter{}
	return &this
}

func (o KalturaAvnDistributionProfileBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaConfigurableDistributionProfileFilter, errKalturaConfigurableDistributionProfileFilter := json.Marshal(o.KalturaConfigurableDistributionProfileFilter)
	if errKalturaConfigurableDistributionProfileFilter != nil {
		return []byte{}, errKalturaConfigurableDistributionProfileFilter
	}
	errKalturaConfigurableDistributionProfileFilter = json.Unmarshal([]byte(serializedKalturaConfigurableDistributionProfileFilter), &toSerialize)
	if errKalturaConfigurableDistributionProfileFilter != nil {
		return []byte{}, errKalturaConfigurableDistributionProfileFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaAvnDistributionProfileBaseFilter struct {
	value *KalturaAvnDistributionProfileBaseFilter
	isSet bool
}

func (v NullableKalturaAvnDistributionProfileBaseFilter) Get() *KalturaAvnDistributionProfileBaseFilter {
	return v.value
}

func (v *NullableKalturaAvnDistributionProfileBaseFilter) Set(val *KalturaAvnDistributionProfileBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaAvnDistributionProfileBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaAvnDistributionProfileBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaAvnDistributionProfileBaseFilter(val *KalturaAvnDistributionProfileBaseFilter) *NullableKalturaAvnDistributionProfileBaseFilter {
	return &NullableKalturaAvnDistributionProfileBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaAvnDistributionProfileBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaAvnDistributionProfileBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


