/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DoubleClickGetFeedByEntryIdRequest struct for DoubleClickGetFeedByEntryIdRequest
type DoubleClickGetFeedByEntryIdRequest struct {
	DistributionProfileId int32 `json:"distributionProfileId"`
	EntryId string `json:"entryId"`
	Hash string `json:"hash"`
	Version *int32 `json:"version,omitempty"`
}

// NewDoubleClickGetFeedByEntryIdRequest instantiates a new DoubleClickGetFeedByEntryIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDoubleClickGetFeedByEntryIdRequest(distributionProfileId int32, entryId string, hash string) *DoubleClickGetFeedByEntryIdRequest {
	this := DoubleClickGetFeedByEntryIdRequest{}
	this.DistributionProfileId = distributionProfileId
	this.EntryId = entryId
	this.Hash = hash
	return &this
}

// NewDoubleClickGetFeedByEntryIdRequestWithDefaults instantiates a new DoubleClickGetFeedByEntryIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDoubleClickGetFeedByEntryIdRequestWithDefaults() *DoubleClickGetFeedByEntryIdRequest {
	this := DoubleClickGetFeedByEntryIdRequest{}
	return &this
}

// GetDistributionProfileId returns the DistributionProfileId field value
func (o *DoubleClickGetFeedByEntryIdRequest) GetDistributionProfileId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DistributionProfileId
}

// GetDistributionProfileIdOk returns a tuple with the DistributionProfileId field value
// and a boolean to check if the value has been set.
func (o *DoubleClickGetFeedByEntryIdRequest) GetDistributionProfileIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistributionProfileId, true
}

// SetDistributionProfileId sets field value
func (o *DoubleClickGetFeedByEntryIdRequest) SetDistributionProfileId(v int32) {
	o.DistributionProfileId = v
}

// GetEntryId returns the EntryId field value
func (o *DoubleClickGetFeedByEntryIdRequest) GetEntryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntryId
}

// GetEntryIdOk returns a tuple with the EntryId field value
// and a boolean to check if the value has been set.
func (o *DoubleClickGetFeedByEntryIdRequest) GetEntryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryId, true
}

// SetEntryId sets field value
func (o *DoubleClickGetFeedByEntryIdRequest) SetEntryId(v string) {
	o.EntryId = v
}

// GetHash returns the Hash field value
func (o *DoubleClickGetFeedByEntryIdRequest) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *DoubleClickGetFeedByEntryIdRequest) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *DoubleClickGetFeedByEntryIdRequest) SetHash(v string) {
	o.Hash = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *DoubleClickGetFeedByEntryIdRequest) GetVersion() int32 {
	if o == nil || o.Version == nil {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DoubleClickGetFeedByEntryIdRequest) GetVersionOk() (*int32, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *DoubleClickGetFeedByEntryIdRequest) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *DoubleClickGetFeedByEntryIdRequest) SetVersion(v int32) {
	o.Version = &v
}

func (o DoubleClickGetFeedByEntryIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["distributionProfileId"] = o.DistributionProfileId
	}
	if true {
		toSerialize["entryId"] = o.EntryId
	}
	if true {
		toSerialize["hash"] = o.Hash
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableDoubleClickGetFeedByEntryIdRequest struct {
	value *DoubleClickGetFeedByEntryIdRequest
	isSet bool
}

func (v NullableDoubleClickGetFeedByEntryIdRequest) Get() *DoubleClickGetFeedByEntryIdRequest {
	return v.value
}

func (v *NullableDoubleClickGetFeedByEntryIdRequest) Set(val *DoubleClickGetFeedByEntryIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDoubleClickGetFeedByEntryIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDoubleClickGetFeedByEntryIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDoubleClickGetFeedByEntryIdRequest(val *DoubleClickGetFeedByEntryIdRequest) *NullableDoubleClickGetFeedByEntryIdRequest {
	return &NullableDoubleClickGetFeedByEntryIdRequest{value: val, isSet: true}
}

func (v NullableDoubleClickGetFeedByEntryIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDoubleClickGetFeedByEntryIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


