/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaScheduleEventResourceBaseFilter `abstract`
type KalturaScheduleEventResourceBaseFilter struct {
	KalturaRelatedFilter
}

// NewKalturaScheduleEventResourceBaseFilter instantiates a new KalturaScheduleEventResourceBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaScheduleEventResourceBaseFilter() *KalturaScheduleEventResourceBaseFilter {
	this := KalturaScheduleEventResourceBaseFilter{}
	return &this
}

// NewKalturaScheduleEventResourceBaseFilterWithDefaults instantiates a new KalturaScheduleEventResourceBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaScheduleEventResourceBaseFilterWithDefaults() *KalturaScheduleEventResourceBaseFilter {
	this := KalturaScheduleEventResourceBaseFilter{}
	return &this
}

func (o KalturaScheduleEventResourceBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaRelatedFilter, errKalturaRelatedFilter := json.Marshal(o.KalturaRelatedFilter)
	if errKalturaRelatedFilter != nil {
		return []byte{}, errKalturaRelatedFilter
	}
	errKalturaRelatedFilter = json.Unmarshal([]byte(serializedKalturaRelatedFilter), &toSerialize)
	if errKalturaRelatedFilter != nil {
		return []byte{}, errKalturaRelatedFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaScheduleEventResourceBaseFilter struct {
	value *KalturaScheduleEventResourceBaseFilter
	isSet bool
}

func (v NullableKalturaScheduleEventResourceBaseFilter) Get() *KalturaScheduleEventResourceBaseFilter {
	return v.value
}

func (v *NullableKalturaScheduleEventResourceBaseFilter) Set(val *KalturaScheduleEventResourceBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaScheduleEventResourceBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaScheduleEventResourceBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaScheduleEventResourceBaseFilter(val *KalturaScheduleEventResourceBaseFilter) *NullableKalturaScheduleEventResourceBaseFilter {
	return &NullableKalturaScheduleEventResourceBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaScheduleEventResourceBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaScheduleEventResourceBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


