/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaFtpDistributionProvider struct for KalturaFtpDistributionProvider
type KalturaFtpDistributionProvider struct {
	KalturaDistributionProvider
}

// NewKalturaFtpDistributionProvider instantiates a new KalturaFtpDistributionProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaFtpDistributionProvider() *KalturaFtpDistributionProvider {
	this := KalturaFtpDistributionProvider{}
	return &this
}

// NewKalturaFtpDistributionProviderWithDefaults instantiates a new KalturaFtpDistributionProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaFtpDistributionProviderWithDefaults() *KalturaFtpDistributionProvider {
	this := KalturaFtpDistributionProvider{}
	return &this
}

func (o KalturaFtpDistributionProvider) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaDistributionProvider, errKalturaDistributionProvider := json.Marshal(o.KalturaDistributionProvider)
	if errKalturaDistributionProvider != nil {
		return []byte{}, errKalturaDistributionProvider
	}
	errKalturaDistributionProvider = json.Unmarshal([]byte(serializedKalturaDistributionProvider), &toSerialize)
	if errKalturaDistributionProvider != nil {
		return []byte{}, errKalturaDistributionProvider
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaFtpDistributionProvider struct {
	value *KalturaFtpDistributionProvider
	isSet bool
}

func (v NullableKalturaFtpDistributionProvider) Get() *KalturaFtpDistributionProvider {
	return v.value
}

func (v *NullableKalturaFtpDistributionProvider) Set(val *KalturaFtpDistributionProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaFtpDistributionProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaFtpDistributionProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaFtpDistributionProvider(val *KalturaFtpDistributionProvider) *NullableKalturaFtpDistributionProvider {
	return &NullableKalturaFtpDistributionProvider{value: val, isSet: true}
}

func (v NullableKalturaFtpDistributionProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaFtpDistributionProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


