/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaConversionProfileBaseFilter `abstract`
type KalturaConversionProfileBaseFilter struct {
	KalturaRelatedFilter
}

// NewKalturaConversionProfileBaseFilter instantiates a new KalturaConversionProfileBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaConversionProfileBaseFilter() *KalturaConversionProfileBaseFilter {
	this := KalturaConversionProfileBaseFilter{}
	return &this
}

// NewKalturaConversionProfileBaseFilterWithDefaults instantiates a new KalturaConversionProfileBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaConversionProfileBaseFilterWithDefaults() *KalturaConversionProfileBaseFilter {
	this := KalturaConversionProfileBaseFilter{}
	return &this
}

func (o KalturaConversionProfileBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaRelatedFilter, errKalturaRelatedFilter := json.Marshal(o.KalturaRelatedFilter)
	if errKalturaRelatedFilter != nil {
		return []byte{}, errKalturaRelatedFilter
	}
	errKalturaRelatedFilter = json.Unmarshal([]byte(serializedKalturaRelatedFilter), &toSerialize)
	if errKalturaRelatedFilter != nil {
		return []byte{}, errKalturaRelatedFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaConversionProfileBaseFilter struct {
	value *KalturaConversionProfileBaseFilter
	isSet bool
}

func (v NullableKalturaConversionProfileBaseFilter) Get() *KalturaConversionProfileBaseFilter {
	return v.value
}

func (v *NullableKalturaConversionProfileBaseFilter) Set(val *KalturaConversionProfileBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaConversionProfileBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaConversionProfileBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaConversionProfileBaseFilter(val *KalturaConversionProfileBaseFilter) *NullableKalturaConversionProfileBaseFilter {
	return &NullableKalturaConversionProfileBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaConversionProfileBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaConversionProfileBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


