/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaBulkUploadVendorCatalogItemData This class represents object-specific data passed to the  bulk upload job.
type KalturaBulkUploadVendorCatalogItemData struct {
	KalturaBulkUploadObjectData
}

// NewKalturaBulkUploadVendorCatalogItemData instantiates a new KalturaBulkUploadVendorCatalogItemData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaBulkUploadVendorCatalogItemData() *KalturaBulkUploadVendorCatalogItemData {
	this := KalturaBulkUploadVendorCatalogItemData{}
	return &this
}

// NewKalturaBulkUploadVendorCatalogItemDataWithDefaults instantiates a new KalturaBulkUploadVendorCatalogItemData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaBulkUploadVendorCatalogItemDataWithDefaults() *KalturaBulkUploadVendorCatalogItemData {
	this := KalturaBulkUploadVendorCatalogItemData{}
	return &this
}

func (o KalturaBulkUploadVendorCatalogItemData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaBulkUploadObjectData, errKalturaBulkUploadObjectData := json.Marshal(o.KalturaBulkUploadObjectData)
	if errKalturaBulkUploadObjectData != nil {
		return []byte{}, errKalturaBulkUploadObjectData
	}
	errKalturaBulkUploadObjectData = json.Unmarshal([]byte(serializedKalturaBulkUploadObjectData), &toSerialize)
	if errKalturaBulkUploadObjectData != nil {
		return []byte{}, errKalturaBulkUploadObjectData
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaBulkUploadVendorCatalogItemData struct {
	value *KalturaBulkUploadVendorCatalogItemData
	isSet bool
}

func (v NullableKalturaBulkUploadVendorCatalogItemData) Get() *KalturaBulkUploadVendorCatalogItemData {
	return v.value
}

func (v *NullableKalturaBulkUploadVendorCatalogItemData) Set(val *KalturaBulkUploadVendorCatalogItemData) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaBulkUploadVendorCatalogItemData) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaBulkUploadVendorCatalogItemData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaBulkUploadVendorCatalogItemData(val *KalturaBulkUploadVendorCatalogItemData) *NullableKalturaBulkUploadVendorCatalogItemData {
	return &NullableKalturaBulkUploadVendorCatalogItemData{value: val, isSet: true}
}

func (v NullableKalturaBulkUploadVendorCatalogItemData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaBulkUploadVendorCatalogItemData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


