/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BatchUpdateExclusiveConvertCollectionJobRequest struct for BatchUpdateExclusiveConvertCollectionJobRequest
type BatchUpdateExclusiveConvertCollectionJobRequest struct {
	FlavorsData []KalturaConvertCollectionFlavorData `json:"flavorsData,omitempty"`
	Id int32 `json:"id"`
	Job KalturaBatchJob `json:"job"`
	LockKey KalturaExclusiveLockKey `json:"lockKey"`
}

// NewBatchUpdateExclusiveConvertCollectionJobRequest instantiates a new BatchUpdateExclusiveConvertCollectionJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchUpdateExclusiveConvertCollectionJobRequest(id int32, job KalturaBatchJob, lockKey KalturaExclusiveLockKey) *BatchUpdateExclusiveConvertCollectionJobRequest {
	this := BatchUpdateExclusiveConvertCollectionJobRequest{}
	this.Id = id
	this.Job = job
	this.LockKey = lockKey
	return &this
}

// NewBatchUpdateExclusiveConvertCollectionJobRequestWithDefaults instantiates a new BatchUpdateExclusiveConvertCollectionJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchUpdateExclusiveConvertCollectionJobRequestWithDefaults() *BatchUpdateExclusiveConvertCollectionJobRequest {
	this := BatchUpdateExclusiveConvertCollectionJobRequest{}
	return &this
}

// GetFlavorsData returns the FlavorsData field value if set, zero value otherwise.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetFlavorsData() []KalturaConvertCollectionFlavorData {
	if o == nil || o.FlavorsData == nil {
		var ret []KalturaConvertCollectionFlavorData
		return ret
	}
	return o.FlavorsData
}

// GetFlavorsDataOk returns a tuple with the FlavorsData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetFlavorsDataOk() ([]KalturaConvertCollectionFlavorData, bool) {
	if o == nil || o.FlavorsData == nil {
		return nil, false
	}
	return o.FlavorsData, true
}

// HasFlavorsData returns a boolean if a field has been set.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) HasFlavorsData() bool {
	if o != nil && o.FlavorsData != nil {
		return true
	}

	return false
}

// SetFlavorsData gets a reference to the given []KalturaConvertCollectionFlavorData and assigns it to the FlavorsData field.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) SetFlavorsData(v []KalturaConvertCollectionFlavorData) {
	o.FlavorsData = v
}

// GetId returns the Id field value
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) SetId(v int32) {
	o.Id = v
}

// GetJob returns the Job field value
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetJob() KalturaBatchJob {
	if o == nil {
		var ret KalturaBatchJob
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetJobOk() (*KalturaBatchJob, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) SetJob(v KalturaBatchJob) {
	o.Job = v
}

// GetLockKey returns the LockKey field value
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetLockKey() KalturaExclusiveLockKey {
	if o == nil {
		var ret KalturaExclusiveLockKey
		return ret
	}

	return o.LockKey
}

// GetLockKeyOk returns a tuple with the LockKey field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) GetLockKeyOk() (*KalturaExclusiveLockKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LockKey, true
}

// SetLockKey sets field value
func (o *BatchUpdateExclusiveConvertCollectionJobRequest) SetLockKey(v KalturaExclusiveLockKey) {
	o.LockKey = v
}

func (o BatchUpdateExclusiveConvertCollectionJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FlavorsData != nil {
		toSerialize["flavorsData"] = o.FlavorsData
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["job"] = o.Job
	}
	if true {
		toSerialize["lockKey"] = o.LockKey
	}
	return json.Marshal(toSerialize)
}

type NullableBatchUpdateExclusiveConvertCollectionJobRequest struct {
	value *BatchUpdateExclusiveConvertCollectionJobRequest
	isSet bool
}

func (v NullableBatchUpdateExclusiveConvertCollectionJobRequest) Get() *BatchUpdateExclusiveConvertCollectionJobRequest {
	return v.value
}

func (v *NullableBatchUpdateExclusiveConvertCollectionJobRequest) Set(val *BatchUpdateExclusiveConvertCollectionJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchUpdateExclusiveConvertCollectionJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchUpdateExclusiveConvertCollectionJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchUpdateExclusiveConvertCollectionJobRequest(val *BatchUpdateExclusiveConvertCollectionJobRequest) *NullableBatchUpdateExclusiveConvertCollectionJobRequest {
	return &NullableBatchUpdateExclusiveConvertCollectionJobRequest{value: val, isSet: true}
}

func (v NullableBatchUpdateExclusiveConvertCollectionJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchUpdateExclusiveConvertCollectionJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


