/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LikeListRequest struct for LikeListRequest
type LikeListRequest struct {
	Filter *KalturaLikeFilter `json:"filter,omitempty"`
	Pager *KalturaFilterPager `json:"pager,omitempty"`
}

// NewLikeListRequest instantiates a new LikeListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLikeListRequest() *LikeListRequest {
	this := LikeListRequest{}
	return &this
}

// NewLikeListRequestWithDefaults instantiates a new LikeListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLikeListRequestWithDefaults() *LikeListRequest {
	this := LikeListRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *LikeListRequest) GetFilter() KalturaLikeFilter {
	if o == nil || o.Filter == nil {
		var ret KalturaLikeFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikeListRequest) GetFilterOk() (*KalturaLikeFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *LikeListRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given KalturaLikeFilter and assigns it to the Filter field.
func (o *LikeListRequest) SetFilter(v KalturaLikeFilter) {
	o.Filter = &v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *LikeListRequest) GetPager() KalturaFilterPager {
	if o == nil || o.Pager == nil {
		var ret KalturaFilterPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LikeListRequest) GetPagerOk() (*KalturaFilterPager, bool) {
	if o == nil || o.Pager == nil {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *LikeListRequest) HasPager() bool {
	if o != nil && o.Pager != nil {
		return true
	}

	return false
}

// SetPager gets a reference to the given KalturaFilterPager and assigns it to the Pager field.
func (o *LikeListRequest) SetPager(v KalturaFilterPager) {
	o.Pager = &v
}

func (o LikeListRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Pager != nil {
		toSerialize["pager"] = o.Pager
	}
	return json.Marshal(toSerialize)
}

type NullableLikeListRequest struct {
	value *LikeListRequest
	isSet bool
}

func (v NullableLikeListRequest) Get() *LikeListRequest {
	return v.value
}

func (v *NullableLikeListRequest) Set(val *LikeListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLikeListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLikeListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLikeListRequest(val *LikeListRequest) *NullableLikeListRequest {
	return &NullableLikeListRequest{value: val, isSet: true}
}

func (v NullableLikeListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLikeListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


