/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaReportExportResponse struct for KalturaReportExportResponse
type KalturaReportExportResponse struct {
	ReferenceJobId *int32 `json:"referenceJobId,omitempty"`
	ReportEmail *string `json:"reportEmail,omitempty"`
}

// NewKalturaReportExportResponse instantiates a new KalturaReportExportResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaReportExportResponse() *KalturaReportExportResponse {
	this := KalturaReportExportResponse{}
	return &this
}

// NewKalturaReportExportResponseWithDefaults instantiates a new KalturaReportExportResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaReportExportResponseWithDefaults() *KalturaReportExportResponse {
	this := KalturaReportExportResponse{}
	return &this
}

// GetReferenceJobId returns the ReferenceJobId field value if set, zero value otherwise.
func (o *KalturaReportExportResponse) GetReferenceJobId() int32 {
	if o == nil || o.ReferenceJobId == nil {
		var ret int32
		return ret
	}
	return *o.ReferenceJobId
}

// GetReferenceJobIdOk returns a tuple with the ReferenceJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaReportExportResponse) GetReferenceJobIdOk() (*int32, bool) {
	if o == nil || o.ReferenceJobId == nil {
		return nil, false
	}
	return o.ReferenceJobId, true
}

// HasReferenceJobId returns a boolean if a field has been set.
func (o *KalturaReportExportResponse) HasReferenceJobId() bool {
	if o != nil && o.ReferenceJobId != nil {
		return true
	}

	return false
}

// SetReferenceJobId gets a reference to the given int32 and assigns it to the ReferenceJobId field.
func (o *KalturaReportExportResponse) SetReferenceJobId(v int32) {
	o.ReferenceJobId = &v
}

// GetReportEmail returns the ReportEmail field value if set, zero value otherwise.
func (o *KalturaReportExportResponse) GetReportEmail() string {
	if o == nil || o.ReportEmail == nil {
		var ret string
		return ret
	}
	return *o.ReportEmail
}

// GetReportEmailOk returns a tuple with the ReportEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KalturaReportExportResponse) GetReportEmailOk() (*string, bool) {
	if o == nil || o.ReportEmail == nil {
		return nil, false
	}
	return o.ReportEmail, true
}

// HasReportEmail returns a boolean if a field has been set.
func (o *KalturaReportExportResponse) HasReportEmail() bool {
	if o != nil && o.ReportEmail != nil {
		return true
	}

	return false
}

// SetReportEmail gets a reference to the given string and assigns it to the ReportEmail field.
func (o *KalturaReportExportResponse) SetReportEmail(v string) {
	o.ReportEmail = &v
}

func (o KalturaReportExportResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ReferenceJobId != nil {
		toSerialize["referenceJobId"] = o.ReferenceJobId
	}
	if o.ReportEmail != nil {
		toSerialize["reportEmail"] = o.ReportEmail
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaReportExportResponse struct {
	value *KalturaReportExportResponse
	isSet bool
}

func (v NullableKalturaReportExportResponse) Get() *KalturaReportExportResponse {
	return v.value
}

func (v *NullableKalturaReportExportResponse) Set(val *KalturaReportExportResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaReportExportResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaReportExportResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaReportExportResponse(val *KalturaReportExportResponse) *NullableKalturaReportExportResponse {
	return &NullableKalturaReportExportResponse{value: val, isSet: true}
}

func (v NullableKalturaReportExportResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaReportExportResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


