/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AnnotationListRequest struct for AnnotationListRequest
type AnnotationListRequest struct {
	Filter *KalturaCuePointFilter `json:"filter,omitempty"`
	Pager *KalturaFilterPager `json:"pager,omitempty"`
}

// NewAnnotationListRequest instantiates a new AnnotationListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnnotationListRequest() *AnnotationListRequest {
	this := AnnotationListRequest{}
	return &this
}

// NewAnnotationListRequestWithDefaults instantiates a new AnnotationListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnnotationListRequestWithDefaults() *AnnotationListRequest {
	this := AnnotationListRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *AnnotationListRequest) GetFilter() KalturaCuePointFilter {
	if o == nil || o.Filter == nil {
		var ret KalturaCuePointFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnnotationListRequest) GetFilterOk() (*KalturaCuePointFilter, bool) {
	if o == nil || o.Filter == nil {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *AnnotationListRequest) HasFilter() bool {
	if o != nil && o.Filter != nil {
		return true
	}

	return false
}

// SetFilter gets a reference to the given KalturaCuePointFilter and assigns it to the Filter field.
func (o *AnnotationListRequest) SetFilter(v KalturaCuePointFilter) {
	o.Filter = &v
}

// GetPager returns the Pager field value if set, zero value otherwise.
func (o *AnnotationListRequest) GetPager() KalturaFilterPager {
	if o == nil || o.Pager == nil {
		var ret KalturaFilterPager
		return ret
	}
	return *o.Pager
}

// GetPagerOk returns a tuple with the Pager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnnotationListRequest) GetPagerOk() (*KalturaFilterPager, bool) {
	if o == nil || o.Pager == nil {
		return nil, false
	}
	return o.Pager, true
}

// HasPager returns a boolean if a field has been set.
func (o *AnnotationListRequest) HasPager() bool {
	if o != nil && o.Pager != nil {
		return true
	}

	return false
}

// SetPager gets a reference to the given KalturaFilterPager and assigns it to the Pager field.
func (o *AnnotationListRequest) SetPager(v KalturaFilterPager) {
	o.Pager = &v
}

func (o AnnotationListRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	if o.Pager != nil {
		toSerialize["pager"] = o.Pager
	}
	return json.Marshal(toSerialize)
}

type NullableAnnotationListRequest struct {
	value *AnnotationListRequest
	isSet bool
}

func (v NullableAnnotationListRequest) Get() *AnnotationListRequest {
	return v.value
}

func (v *NullableAnnotationListRequest) Set(val *AnnotationListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnnotationListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnnotationListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnnotationListRequest(val *AnnotationListRequest) *NullableAnnotationListRequest {
	return &NullableAnnotationListRequest{value: val, isSet: true}
}

func (v NullableAnnotationListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnnotationListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


