/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaSipServerNode struct for KalturaSipServerNode
type KalturaSipServerNode struct {
	KalturaServerNode
}

// NewKalturaSipServerNode instantiates a new KalturaSipServerNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaSipServerNode() *KalturaSipServerNode {
	this := KalturaSipServerNode{}
	return &this
}

// NewKalturaSipServerNodeWithDefaults instantiates a new KalturaSipServerNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaSipServerNodeWithDefaults() *KalturaSipServerNode {
	this := KalturaSipServerNode{}
	return &this
}

func (o KalturaSipServerNode) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaServerNode, errKalturaServerNode := json.Marshal(o.KalturaServerNode)
	if errKalturaServerNode != nil {
		return []byte{}, errKalturaServerNode
	}
	errKalturaServerNode = json.Unmarshal([]byte(serializedKalturaServerNode), &toSerialize)
	if errKalturaServerNode != nil {
		return []byte{}, errKalturaServerNode
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaSipServerNode struct {
	value *KalturaSipServerNode
	isSet bool
}

func (v NullableKalturaSipServerNode) Get() *KalturaSipServerNode {
	return v.value
}

func (v *NullableKalturaSipServerNode) Set(val *KalturaSipServerNode) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaSipServerNode) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaSipServerNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaSipServerNode(val *KalturaSipServerNode) *NullableKalturaSipServerNode {
	return &NullableKalturaSipServerNode{value: val, isSet: true}
}

func (v NullableKalturaSipServerNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaSipServerNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


