/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaDistributionValidationErrorConditionNotMet struct for KalturaDistributionValidationErrorConditionNotMet
type KalturaDistributionValidationErrorConditionNotMet struct {
	KalturaDistributionValidationError
}

// NewKalturaDistributionValidationErrorConditionNotMet instantiates a new KalturaDistributionValidationErrorConditionNotMet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaDistributionValidationErrorConditionNotMet() *KalturaDistributionValidationErrorConditionNotMet {
	this := KalturaDistributionValidationErrorConditionNotMet{}
	return &this
}

// NewKalturaDistributionValidationErrorConditionNotMetWithDefaults instantiates a new KalturaDistributionValidationErrorConditionNotMet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaDistributionValidationErrorConditionNotMetWithDefaults() *KalturaDistributionValidationErrorConditionNotMet {
	this := KalturaDistributionValidationErrorConditionNotMet{}
	return &this
}

func (o KalturaDistributionValidationErrorConditionNotMet) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaDistributionValidationError, errKalturaDistributionValidationError := json.Marshal(o.KalturaDistributionValidationError)
	if errKalturaDistributionValidationError != nil {
		return []byte{}, errKalturaDistributionValidationError
	}
	errKalturaDistributionValidationError = json.Unmarshal([]byte(serializedKalturaDistributionValidationError), &toSerialize)
	if errKalturaDistributionValidationError != nil {
		return []byte{}, errKalturaDistributionValidationError
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaDistributionValidationErrorConditionNotMet struct {
	value *KalturaDistributionValidationErrorConditionNotMet
	isSet bool
}

func (v NullableKalturaDistributionValidationErrorConditionNotMet) Get() *KalturaDistributionValidationErrorConditionNotMet {
	return v.value
}

func (v *NullableKalturaDistributionValidationErrorConditionNotMet) Set(val *KalturaDistributionValidationErrorConditionNotMet) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaDistributionValidationErrorConditionNotMet) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaDistributionValidationErrorConditionNotMet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaDistributionValidationErrorConditionNotMet(val *KalturaDistributionValidationErrorConditionNotMet) *NullableKalturaDistributionValidationErrorConditionNotMet {
	return &NullableKalturaDistributionValidationErrorConditionNotMet{value: val, isSet: true}
}

func (v NullableKalturaDistributionValidationErrorConditionNotMet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaDistributionValidationErrorConditionNotMet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


