/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaLiveAssetBaseFilter `abstract`
type KalturaLiveAssetBaseFilter struct {
	KalturaFlavorAssetFilter
}

// NewKalturaLiveAssetBaseFilter instantiates a new KalturaLiveAssetBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaLiveAssetBaseFilter() *KalturaLiveAssetBaseFilter {
	this := KalturaLiveAssetBaseFilter{}
	return &this
}

// NewKalturaLiveAssetBaseFilterWithDefaults instantiates a new KalturaLiveAssetBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaLiveAssetBaseFilterWithDefaults() *KalturaLiveAssetBaseFilter {
	this := KalturaLiveAssetBaseFilter{}
	return &this
}

func (o KalturaLiveAssetBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaFlavorAssetFilter, errKalturaFlavorAssetFilter := json.Marshal(o.KalturaFlavorAssetFilter)
	if errKalturaFlavorAssetFilter != nil {
		return []byte{}, errKalturaFlavorAssetFilter
	}
	errKalturaFlavorAssetFilter = json.Unmarshal([]byte(serializedKalturaFlavorAssetFilter), &toSerialize)
	if errKalturaFlavorAssetFilter != nil {
		return []byte{}, errKalturaFlavorAssetFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaLiveAssetBaseFilter struct {
	value *KalturaLiveAssetBaseFilter
	isSet bool
}

func (v NullableKalturaLiveAssetBaseFilter) Get() *KalturaLiveAssetBaseFilter {
	return v.value
}

func (v *NullableKalturaLiveAssetBaseFilter) Set(val *KalturaLiveAssetBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaLiveAssetBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaLiveAssetBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaLiveAssetBaseFilter(val *KalturaLiveAssetBaseFilter) *NullableKalturaLiveAssetBaseFilter {
	return &NullableKalturaLiveAssetBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaLiveAssetBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaLiveAssetBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


