/*
Kaltura VPaaS

The Kaltura VPaaS API

API version: 18.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// KalturaWebexDropFolderBaseFilter `abstract`
type KalturaWebexDropFolderBaseFilter struct {
	KalturaDropFolderFilter
}

// NewKalturaWebexDropFolderBaseFilter instantiates a new KalturaWebexDropFolderBaseFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKalturaWebexDropFolderBaseFilter() *KalturaWebexDropFolderBaseFilter {
	this := KalturaWebexDropFolderBaseFilter{}
	return &this
}

// NewKalturaWebexDropFolderBaseFilterWithDefaults instantiates a new KalturaWebexDropFolderBaseFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKalturaWebexDropFolderBaseFilterWithDefaults() *KalturaWebexDropFolderBaseFilter {
	this := KalturaWebexDropFolderBaseFilter{}
	return &this
}

func (o KalturaWebexDropFolderBaseFilter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedKalturaDropFolderFilter, errKalturaDropFolderFilter := json.Marshal(o.KalturaDropFolderFilter)
	if errKalturaDropFolderFilter != nil {
		return []byte{}, errKalturaDropFolderFilter
	}
	errKalturaDropFolderFilter = json.Unmarshal([]byte(serializedKalturaDropFolderFilter), &toSerialize)
	if errKalturaDropFolderFilter != nil {
		return []byte{}, errKalturaDropFolderFilter
	}
	return json.Marshal(toSerialize)
}

type NullableKalturaWebexDropFolderBaseFilter struct {
	value *KalturaWebexDropFolderBaseFilter
	isSet bool
}

func (v NullableKalturaWebexDropFolderBaseFilter) Get() *KalturaWebexDropFolderBaseFilter {
	return v.value
}

func (v *NullableKalturaWebexDropFolderBaseFilter) Set(val *KalturaWebexDropFolderBaseFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableKalturaWebexDropFolderBaseFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableKalturaWebexDropFolderBaseFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKalturaWebexDropFolderBaseFilter(val *KalturaWebexDropFolderBaseFilter) *NullableKalturaWebexDropFolderBaseFilter {
	return &NullableKalturaWebexDropFolderBaseFilter{value: val, isSet: true}
}

func (v NullableKalturaWebexDropFolderBaseFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKalturaWebexDropFolderBaseFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


